-- ============================================================================
-- TRAININGHUB PRO - SEED: LOTES 11-14 DE TAREAS (116-150)
-- ============================================================================
-- 35 tareas finales para completar biblioteca de 150 tareas profesionales
-- ============================================================================

-- ============================================================================
-- JUEGO DE POSICIÓN (JDP) - 6 tareas adicionales (Total: 15)
-- ============================================================================

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, m2_por_jugador, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Construcción 4-3-3 con Extremos Invertidos', 'JDP-010', (SELECT id FROM categorias_tarea WHERE codigo = 'JDP'), '00000000-0000-0000-0000-000000000001', 22, 4, 4.5, 1, 65, 60, 'tres_cuartos_campo', 17, 17, 1, '10+POR vs 6', 'Construcción en 4-3-3 con extremos que invierten posición. Extremos parten abiertos y cortan hacia dentro, laterales suben. Trabajo de amplitud y profundidad.', 'Portero con balón', 'Pase a zona de finalización o robo', '["Extremos invierten cuando balón en lateral", "Laterales dan amplitud cuando extremos cortan"]', 'ataque_organizado', 'Construcción con inversiones', 'Crear superioridad con movimientos de inversión', 'Baja-media intensidad', 55.3, 'baja', 125, 145, 3, '["Extremos: cortar diagonal hacia dentro", "Laterales: subir cuando extremo corta", "Pivotes: escalonar"]', '["Cerrar líneas interiores", "Vigilar laterales que suben"]', '["Inversiones descoordinadas", "Laterales no suben"]', '[{"nombre": "10+POR vs 7", "descripcion": "Más presión", "dificultad": "+1"}]', '["Portería reglamentaria", "Conos", "Petos", "Balones x10"]', '["MD-3", "MD-2"]', true, true, '["4-3-3", "inversión", "extremos", "construcción", "posicional"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, m2_por_jugador, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Salida Portero con Opción Larga', 'JDP-011', (SELECT id FROM categorias_tarea WHERE codigo = 'JDP'), '00000000-0000-0000-0000-000000000001', 18, 6, 2.5, 0.5, 55, 65, 'campo_propio', 12, 12, 1, '6+POR vs 5', 'Salida de balón donde portero debe leer presión: si hay espacio sale en corto, si presión alta puede optar por balón largo a delantero referencia.', 'Portero con balón', 'Superar pressing o balón controlado largo', '["Portero decide: corto o largo", "Si elige largo, delantero debe ganar duelo aéreo"]', 'ataque_organizado', 'Salida adaptativa', 'Elegir mejor opción según presión', 'Baja intensidad', 56.4, 'baja', 115, 140, 3, '["Leer presión antes de decidir", "Si corto: opciones claras", "Si largo: delantero se ofrece"]', '["Variar intensidad de pressing", "Cerrar opciones cortas"]', '["Siempre mismo recurso", "Indecisión"]', '[{"nombre": "Solo corto", "descripcion": "Prohibido largo", "dificultad": "+1"}]', '["Portería reglamentaria", "Conos zona segura", "Petos", "Balones x8"]', '["MD-3", "MD-2"]', true, true, '["salida balón", "largo", "corto", "adaptación", "portero"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Juego Posicional con Cambio de Sistema', 'JDP-012', (SELECT id FROM categorias_tarea WHERE codigo = 'JDP'), '00000000-0000-0000-0000-000000000001', 24, 4, 5, 1, 60, 55, 'tres_cuartos_campo', 18, 18, 1, '10+POR vs 7', 'Trabajo de adaptación táctica. Comenzar en 4-3-3, a señal del entrenador cambiar a 3-4-3 manteniendo posesión. Jugadores deben reposicionarse fluidamente.', 'Portero con balón en 4-3-3', 'Tiempo o pérdida', '["Señal de cambio cada 2 min", "De 4-3-3 a 3-4-3 y viceversa", "Transición fluida"]', 'ataque_organizado', 'Flexibilidad táctica', 'Cambiar sistema manteniendo posesión', 'Media intensidad', 50, 'media', 140, 160, 3, '["Conocer ambas posiciones", "Reposicionarse rápido al cambio", "Comunicar"]', '["Adaptar pressing al sistema rival", "Identificar nuevo sistema"]', '["Confusión en cambio", "No conocer nueva posición"]', '[{"nombre": "3 sistemas", "descripcion": "Añadir 4-4-2", "dificultad": "+1"}]', '["Conos posiciones x10", "Petos 2 colores", "Balones x8"]', '["MD-3", "MD-2"]', true, true, '["cambio sistema", "flexibilidad", "4-3-3", "3-4-3", "táctico"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, m2_por_jugador, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Circulación Rápida en Mediocampo', 'JDP-013', (SELECT id FROM categorias_tarea WHERE codigo = 'JDP'), '00000000-0000-0000-0000-000000000001', 18, 5, 3, 0.75, 35, 30, 'zona_media', 12, 12, 0, '8v4', 'Circulación rápida en zona de mediocampo. 8 poseedores (2 pivotes + 4 interiores + 2 extremos) contra 4 presionadores. Énfasis en velocidad de circulación y triangulaciones.', 'Pivote con balón', '10 pases o robo', '["Máximo 2 toques", "Obligatorio cambiar de lado cada 5 pases"]', 'ataque_organizado', 'Circulación en mediocampo', 'Dominar zona media con velocidad', 'Media-alta intensidad', 27.1, 'media', 150, 170, 2, '["Circular rápido", "Triangular", "Cambiar de lado", "No retener"]', '["Pressing en 4 coordinado", "Cortar cambio de lado"]', '["Retener balón", "No cambiar de lado"]', '[{"nombre": "8v5", "descripcion": "Más presión", "dificultad": "+1"}]', '["Conos zona x8", "Petos 2 colores", "Balones x6"]', '["MD-4", "MD-3"]', true, true, '["circulación", "mediocampo", "velocidad", "triangulaciones"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, m2_por_jugador, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Superioridad en Primera Fase', 'JDP-014', (SELECT id FROM categorias_tarea WHERE codigo = 'JDP'), '00000000-0000-0000-0000-000000000001', 20, 5, 3.5, 0.75, 45, 55, 'campo_propio', 10, 10, 1, '5+POR vs 3', 'Trabajo de superioridad en primera fase de construcción. Portero + 4 defensores + 1 pivote contra 3 delanteros. Objetivo: salir de zona con superioridad clara.', 'Portero con balón', 'Balón en pivote o supera línea', '["Portero cuenta como jugador", "6v3 superioridad clara", "Pivote debe recibir al menos 1 vez"]', 'ataque_organizado', 'Superioridad en salida', 'Aprovechar 6v3 para salir limpio', 'Baja intensidad', 54.5, 'baja', 115, 135, 2, '["Portero como opción constante", "Centrales abiertos", "Pivote ofrecerse entre líneas"]', '["Pressing coordinado en 3", "Forzar balón largo"]', '["No usar al portero", "Pivote escondido"]', '[{"nombre": "5+POR vs 4", "descripcion": "Menos superioridad", "dificultad": "+1"}]', '["Portería reglamentaria", "Conos zona", "Petos", "Balones x8"]', '["MD-3", "MD-2"]', true, true, '["superioridad", "primera fase", "6v3", "salida"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Progresión por Carril Central', 'JDP-015', (SELECT id FROM categorias_tarea WHERE codigo = 'JDP'), '00000000-0000-0000-0000-000000000001', 20, 5, 3.5, 0.75, 50, 40, 'rectangular', 14, 14, 1, '8+POR vs 5', 'Trabajo de progresión por carril central. Campo dividido en 3 carriles verticales. Punto extra si la progresión final pasa por carril central. Trabaja juego interior.', 'Portero con balón', 'Gol o llegada a zona final', '["Bonus si progresión por carril central", "Carril central = 10m de ancho en medio"]', 'ataque_organizado', 'Juego interior', 'Progresar por el centro del campo', 'Media intensidad', 'media', 140, 160, 3, '["Buscar carril central para bonus", "Mediapunta referencia", "Paredes en zona interior"]', '["Cerrar carril central", "Forzar por bandas"]', '["Solo jugar por fuera", "No buscar central"]', '[{"nombre": "Sin bonus", "descripcion": "Igual valor todas zonas", "dificultad": "-1"}]', '["Portería reglamentaria", "Conos carriles", "Petos", "Balones x10"]', '["MD-3", "MD-2"]', true, true, '["carril central", "interior", "progresión", "mediapunta"]');

-- ============================================================================
-- POSESIÓN (POS) - 5 tareas adicionales (Total: 18)
-- ============================================================================

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, forma_puntuar, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, m2_por_jugador, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Posesión 8v4 con Transición', 'POS-014', (SELECT id FROM categorias_tarea WHERE codigo = 'POS'), '00000000-0000-0000-0000-000000000001', 18, 4, 3.5, 1, 30, 25, 'rectangular', 12, 12, 0, '8v4', 'Posesión 8v4 con transición al robo. Al robar, los 4 defensores deben completar 3 pases entre ellos para sumar punto antes de que los 8 recuperen.', 'Entrenador pasa al equipo de 8', 'Tiempo de serie', '["8v4 en posesión", "Al robo: 4 tienen 10 seg para hacer 3 pases", "8 presionan para recuperar"]', '10 pases del 8 = 1pt, 3 pases del 4 tras robo = 1pt', 'transicion_defensa_ataque', 'Posesión con transición', 'Mantener y transicionar rápido', 'Media-alta intensidad', 31.3, 'alta', 155, 175, 2, '["Mantener 10 pases", "Si pierden: pressing inmediato"]', '["Robar y consolidar con 3 pases", "Transición rápida"]', '["No presionar tras pérdida", "Transición lenta del equipo de 4"]', '[{"nombre": "8v3", "descripcion": "Más superioridad", "dificultad": "-1"}]', '["Conos x8", "Petos 2 colores", "Balones x6"]', '["MD-4", "MD-3"]', true, true, '["posesión", "transición", "8v4", "consolidar"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, forma_puntuar, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, m2_por_jugador, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Posesión con Apoyo Diagonal', 'POS-015', (SELECT id FROM categorias_tarea WHERE codigo = 'POS'), '00000000-0000-0000-0000-000000000001', 16, 4, 3, 1, 35, 30, 'rectangular', 10, 10, 0, '6v4', 'Posesión 6v4 donde los apoyos deben ser siempre en diagonal. Prohibido pases horizontales o verticales puros. Trabaja triangulaciones y diagonales.', 'Entrenador pasa al equipo de 6', '8 pases o robo', '["Solo pases en diagonal", "Pase horizontal/vertical = pérdida"]', '8 pases en diagonal = 1 punto', 'ataque_organizado', 'Apoyos diagonales', 'Triangular siempre en diagonal', 'Media intensidad', 35, 'media', 145, 165, 2, '["Posicionarse en diagonal del balón", "No estar en línea", "Triangular constantemente"]', '["Cortar diagonales", "Forzar pase recto"]', '["Posición en línea", "Pase no diagonal"]', '[{"nombre": "Libre de pases", "descripcion": "Sin restricción", "dificultad": "-1"}]', '["Conos x8", "Petos 2 colores", "Balones x6"]', '["MD-4", "MD-3"]', true, true, '["diagonal", "triangulación", "posesión", "apoyo"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, forma_puntuar, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, m2_por_jugador, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Posesión con Zonas Prohibidas', 'POS-016', (SELECT id FROM categorias_tarea WHERE codigo = 'POS'), '00000000-0000-0000-0000-000000000001', 20, 4, 4, 1, 40, 35, 'rectangular', 12, 12, 0, '6v6', 'Posesión 6v6 con 2 zonas prohibidas (marcadas con conos) que van cambiando cada minuto. No se puede entrar ni pasar por esas zonas. Trabaja adaptación espacial.', 'Entrenador pasa balón', 'Tiempo de serie', '["2 zonas prohibidas de 5x5m", "Cambian cada 60 seg", "Pasar por zona prohibida = pérdida"]', '10 pases sin usar zonas prohibidas = 1 punto', 'ataque_organizado', 'Adaptación espacial', 'Poseer evitando zonas cambiantes', 'Media intensidad', 33.3, 'media', 145, 165, 2, '["Identificar zonas prohibidas", "Adaptarse cuando cambian", "Usar espacio disponible"]', '["Orientar hacia zonas prohibidas", "Forzar error"]', '["Entrar en zona prohibida", "No adaptarse al cambio"]', '[{"nombre": "3 zonas", "descripcion": "Más restricción", "dificultad": "+1"}]', '["Conos normales + conos especiales zonas", "Petos 2 colores", "Balones x6"]', '["MD-4", "MD-3"]', true, true, '["zonas prohibidas", "adaptación", "posesión", "espacial"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, forma_puntuar, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, m2_por_jugador, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Posesión con Jugador Infiltrado', 'POS-017', (SELECT id FROM categorias_tarea WHERE codigo = 'POS'), '00000000-0000-0000-0000-000000000001', 18, 4, 3.5, 1, 35, 30, 'rectangular', 11, 11, 0, '5v4+2 infiltrados', 'Posesión con 2 infiltrados: 1 jugador de cada equipo empieza en el campo contrario como infiltrado. Pueden recibir para crear superioridad momentánea.', 'Entrenador pasa balón', 'Tiempo de serie', '["1 infiltrado por equipo en campo rival", "Infiltrado puede recibir (crea 6v4)", "Infiltrado máximo 2 toques"]', 'Pase exitoso al infiltrado = 1 punto', 'ataque_organizado', 'Uso de infiltrado', 'Crear superioridad con infiltrado', 'Media intensidad', 31.8, 'media', 145, 165, 2, '["Buscar al infiltrado", "Infiltrado ofrecerse", "Usar superioridad"]', '["Vigilar infiltrado propio", "Presionar cuando recibe infiltrado rival"]', '["No usar infiltrado", "Infiltrado mal posicionado"]', '[{"nombre": "Sin infiltrados", "descripcion": "Posesión normal", "dificultad": "-1"}]', '["Conos x8", "Petos 2 colores + peto especial", "Balones x6"]', '["MD-4", "MD-3"]', true, true, '["infiltrado", "superioridad", "posesión", "especial"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, forma_puntuar, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, m2_por_jugador, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Posesión 7v7 Campo Grande', 'POS-018', (SELECT id FROM categorias_tarea WHERE codigo = 'POS'), '00000000-0000-0000-0000-000000000001', 22, 4, 4.5, 1, 55, 45, 'rectangular', 14, 14, 0, '7v7', 'Posesión 7v7 en espacio grande. Sin comodines, pura posesión en igualdad. Trabaja posesión en condiciones de partido real sin ventaja numérica.', 'Saque lateral', 'Tiempo de serie', '["Posesión en igualdad 7v7", "15 pases = punto", "Sin límite de toques"]', '15 pases consecutivos = 1 punto', 'ataque_organizado', 'Posesión en igualdad', 'Dominar sin ventaja numérica', 'Alta intensidad', 35.4, 'alta', 155, 175, 2, '["Usar todo el espacio", "Paciencia", "Movilidad constante", "Cambiar orientación"]', '["Pressing coordinado", "Compactar", "Forzar error"]', '["No usar amplitud", "Precipitarse"]', '[{"nombre": "6v6", "descripcion": "Menos jugadores", "dificultad": "+1"}]', '["Conos x8", "Petos 2 colores", "Balones x8"]', '["MD-4", "MD-3"]', true, true, '["posesión", "igualdad", "7v7", "real"]');

-- ============================================================================
-- PARTIDO CONDICIONADO (PCO) - 6 tareas adicionales (Total: 18)
-- ============================================================================

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, forma_puntuar, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Partido 6v6 Solo Pie Débil', 'PCO-013', (SELECT id FROM categorias_tarea WHERE codigo = 'PCO'), '00000000-0000-0000-0000-000000000001', 20, 2, 8, 2, 50, 40, 'campo_reducido', 14, 14, 2, '6v6+2POR', 'Partido donde SOLO se puede usar el pie no dominante. Goles con pie dominante no valen. Trabaja pie débil en contexto de partido.', 'Saque de portero', 'Tiempo de serie', '["Solo pie no dominante", "Gol con dominante = no vale", "Portero libre"]', 'Gol con pie débil = 1 punto', 'ataque_organizado', 'Mejora técnica pie débil', 'Jugar con pie no dominante', 'Media intensidad', 'media', 145, 165, 2, '["Usar solo pie débil", "Perfilarse para pie débil"]', '["Forzar errores de pie débil"]', '["Usar pie dominante", "No perfilarse"]', '[{"nombre": "Libre", "descripcion": "Sin restricción", "dificultad": "-1"}]', '["Porterías reducidas", "Petos", "Balones x8"]', '["MD-4", "MD-3"]', true, true, '["pie débil", "técnica", "condicionado"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, forma_puntuar, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Partido 7v7 Todos Tocan', 'PCO-014', (SELECT id FROM categorias_tarea WHERE codigo = 'PCO'), '00000000-0000-0000-0000-000000000001', 24, 2, 10, 2, 55, 45, 'campo_reducido', 16, 16, 2, '7v7+2POR', 'Partido donde el gol solo vale si TODOS los jugadores de campo tocaron el balón en la jugada. Trabaja participación colectiva.', 'Saque de centro', 'Tiempo de serie', '["Gol solo vale si los 7 tocaron", "Reinicio: cuenta se resetea", "Portero no cuenta"]', 'Gol con todos = 1 punto, Gol sin todos = 0 puntos', 'ataque_organizado', 'Participación colectiva', 'Involucrar a todos en el juego', 'Alta intensidad', 'alta', 155, 175, 2, '["Circular para que todos toquen", "No dejar a nadie fuera", "Comunicar quién falta"]', '["Presionar para evitar circulación completa"]', '["Olvidar a alguno", "Gol sin todos"]', '[{"nombre": "5 de 7 tocan", "descripcion": "Menos exigente", "dificultad": "-1"}]', '["Porterías reducidas", "Petos", "Balones x8"]', '["MD-4", "MD-3"]', true, true, '["todos tocan", "colectivo", "circulación", "condicionado"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, forma_puntuar, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Partido 8v8 Defensa a Medio Campo', 'PCO-015', (SELECT id FROM categorias_tarea WHERE codigo = 'PCO'), '00000000-0000-0000-0000-000000000001', 26, 2, 11, 2, 70, 55, 'campo_reducido', 18, 18, 2, '8v8+2POR', 'Partido donde el equipo sin balón solo puede defender de medio campo hacia atrás. Prohibido presionar en campo rival. Trabaja bloque bajo.', 'Saque de portero', 'Tiempo de serie', '["Defensa solo en campo propio", "Prohibido pressing en campo rival", "Línea de fuera de juego activa"]', 'Gol = 1 punto', 'defensa_organizada', 'Defensa en bloque bajo', 'Defender sin presionar alto', 'Media-alta intensidad', 'alta', 155, 175, 2, '["Construcción libre en campo", "Buscar huecos en bloque bajo"]', '["Organizar bloque bajo", "No presionar adelante", "Esperar en campo propio"]', '["Presionar en campo rival", "Bloque desorganizado"]', '[{"nombre": "Pressing libre", "descripcion": "Sin restricción", "dificultad": "-1"}]', '["Porterías reglamentarias", "Conos medio campo", "Petos", "Balones x10"]', '["MD-3", "MD-2"]', true, true, '["bloque bajo", "defensa", "medio campo", "condicionado"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, forma_puntuar, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Partido 5v5 con Portero Móvil', 'PCO-016', (SELECT id FROM categorias_tarea WHERE codigo = 'PCO'), '00000000-0000-0000-0000-000000000001', 20, 4, 4, 1, 40, 30, 'rectangular', 12, 12, 2, '5v5+2POR', 'Partido donde los porteros pueden moverse por la línea de fondo (no solo en la portería). Portería = toda la línea de fondo. Trabaja cobertura defensiva.', 'Saque de portero', 'Gol o tiempo', '["Portería = toda la línea de fondo", "Portero se mueve por toda la línea", "Gol solo desde zona de tiro (últimos 10m)"]', 'Gol en línea de fondo = 1 punto', 'ataque_organizado', 'Finalización creativa', 'Buscar hueco en línea de fondo', 'Alta intensidad', 'alta', 160, 180, 2, '["Buscar hueco donde no esté portero", "Desplazamiento para abrir ángulo"]', '["Portero: cubrir zona probable de tiro", "Defensores: no dejar tiro fácil"]', '["Tirar donde está portero", "Portero mal posicionado"]', '[{"nombre": "Portero fijo", "descripcion": "Normal", "dificultad": "-1"}]', '["Conos línea de fondo", "Petos", "Balones x8"]', '["MD-4", "MD-3"]', true, true, '["portero móvil", "línea de fondo", "creatividad", "condicionado"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, forma_puntuar, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Partido 6v6 con Asistente Obligatorio', 'PCO-017', (SELECT id FROM categorias_tarea WHERE codigo = 'PCO'), '00000000-0000-0000-0000-000000000001', 22, 2, 9, 2, 50, 40, 'campo_reducido', 14, 14, 2, '6v6+2POR', 'Partido donde el gol solo vale con asistencia (no valen goles individuales). Trabaja el último pase y la combinación final.', 'Saque de portero', 'Tiempo de serie', '["Gol solo válido con asistencia", "Gol individual = no vale", "Asistencia = último pase antes de gol"]', 'Gol con asistencia = 1 punto', 'ataque_organizado', 'Juego asociativo', 'Generar gol con asistencia', 'Alta intensidad', 'alta', 155, 175, 2, '["Buscar el pase de gol", "No finalizar solo", "Combinación final"]', '["Cerrar líneas de pase final", "Anticipar asistencia"]', '["Finalizar solo", "No buscar asistencia"]', '[{"nombre": "Gol libre", "descripcion": "Sin restricción", "dificultad": "-1"}]', '["Porterías reducidas", "Petos", "Balones x8"]', '["MD-4", "MD-3"]', true, true, '["asistencia", "último pase", "combinación", "condicionado"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, forma_puntuar, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Partido 7v7 Cambio Continuo', 'PCO-018', (SELECT id FROM categorias_tarea WHERE codigo = 'PCO'), '00000000-0000-0000-0000-000000000001', 25, 1, 23, 2, 55, 45, 'campo_reducido', 18, 20, 2, '7v7+2POR con rotación', 'Partido con cambios continuos. Cada gol = cambio obligatorio de 2 jugadores por equipo. Jugadores en espera preparados para entrar. Simula gestión de banquillo.', 'Saque de centro', 'Tiempo total', '["Tras cada gol: salen 2, entran 2", "Cambio en 10 segundos", "Jugadores en espera preparados"]', 'Goles acumulados', 'transicion_defensa_ataque', 'Gestión de cambios', 'Mantener intensidad con rotación', 'Alta intensidad', 'alta', 160, 180, 1, '["Estar siempre preparado", "Entrar con intensidad", "Adaptarse rápido"]', '["Cubrir al que entra", "Organización rápida tras cambio"]', '["Cambio lento", "Entrar sin intensidad"]', '[{"nombre": "Sin cambios", "descripcion": "Equipos fijos", "dificultad": "-1"}]', '["Porterías reducidas", "Petos", "Balones x8"]', '["MD-4"]', true, true, '["cambios", "rotación", "intensidad", "gestión"]');

-- ============================================================================
-- RONDOS (RND) - 3 tareas adicionales (Total: 18)
-- ============================================================================

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, forma_puntuar, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, m2_por_jugador, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Rondo 6v2 con Portería de Escape', 'RND-016', (SELECT id FROM categorias_tarea WHERE codigo = 'RND'), '00000000-0000-0000-0000-000000000001', 14, 5, 2, 0.75, 15, 15, 'cuadrado', 8, 8, 0, '6v2', 'Rondo 6v2 con mini portería en un lado. Los defensores pueden escapar del pressing haciendo gol en la portería tras robar. Trabaja transición inmediata.', 'Entrenador pasa al equipo de 6', '10 pases o gol de escape', '["6v2 rondo normal", "Si 2 roban: pueden hacer gol en mini portería", "Gol de escape = victoria inmediata"]', '10 pases = 1pt poseedores, Gol escape = 2pts defensores', 'transicion_defensa_ataque', 'Rondo con transición', 'Transicionar tras robo', 'Alta intensidad', 28.1, 'alta', 160, 180, 2, '["No perder en transición", "Pressing inmediato si pierden"]', '["Robar y atacar portería", "Transición rápida"]', '["No presionar tras pérdida", "No atacar portería tras robo"]', '[{"nombre": "Sin portería", "descripcion": "Rondo clásico", "dificultad": "-1"}]', '["Mini portería x1", "Conos x4", "Petos 2 colores", "Balones x6"]', '["MD-4", "MD-3"]', true, true, '["rondo", "escape", "transición", "mini portería"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, forma_puntuar, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, m2_por_jugador, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Rondo 5v2+2 con Relevo', 'RND-017', (SELECT id FROM categorias_tarea WHERE codigo = 'RND'), '00000000-0000-0000-0000-000000000001', 16, 4, 3, 1, 14, 14, 'cuadrado', 9, 9, 0, '5v2+2 en espera', 'Rondo 5v2 donde cada 30 segundos los 2 defensores hacen relevo con los 2 en espera. Mantiene intensidad alta en pressing.', 'Entrenador pasa al equipo de 5', 'Tiempo de serie', '["2 defienden, 2 esperan", "Relevo cada 30 seg", "Defensores que salen van a espera"]', 'Robos acumulados por pareja de defensores', 'ataque_organizado', 'Pressing intenso con relevo', 'Mantener pressing fresco', 'Muy alta intensidad', 21.8, 'alta', 165, 185, 2, '["Mantener posesión contra pressing fresco"]', '["30 seg de pressing máximo", "Robar antes del relevo"]', '["Bajar intensidad antes de relevo"]', '[{"nombre": "Relevo cada 20 seg", "descripcion": "Más frecuente", "dificultad": "+1"}]', '["Conos x4", "Petos 2 colores", "Balones x4", "Silbato"]', '["MD-4"]', true, true, '["rondo", "relevo", "pressing", "intensidad"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, forma_puntuar, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, m2_por_jugador, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Rondo Klopp: 4v4+4 Tres Equipos', 'RND-018', (SELECT id FROM categorias_tarea WHERE codigo = 'RND'), '00000000-0000-0000-0000-000000000001', 18, 3, 5, 1, 25, 25, 'cuadrado', 12, 12, 0, '4v4+4 (tres equipos)', 'Rondo estilo Klopp con 3 equipos de 4. Dos equipos juegan 8v4, el que pierde balón pasa a defender. Gegenpressing: al perder, 6 segundos de pressing máximo.', 'Entrenador pasa a un equipo', 'Tiempo de serie', '["2 equipos atacan (8v4)", "Equipo que pierde: pasa a defender", "6 seg de gegenpressing tras pérdida"]', 'Robos por equipo', 'transicion_ataque_defensa', 'Gegenpressing Klopp', 'Pressing tras pérdida inmediato', 'Muy alta intensidad', 52.1, 'alta', 170, 190, 2, '["No perder", "Si pierden: 6 seg pressing máximo"]', '["Robar rápido para no ser equipo defensor"]', '["Gegenpressing lento", "No presionar tras pérdida"]', '[{"nombre": "Sin gegenpressing", "descripcion": "Cambio normal", "dificultad": "-1"}]', '["Conos x4", "Petos 3 colores", "Balones x6", "Cronómetro"]', '["MD-4", "MD-3"]', true, true, '["Klopp", "gegenpressing", "tres equipos", "intensidad"]');

-- ============================================================================
-- BALÓN PARADO (ABP) - 5 tareas adicionales (Total: 18)
-- ============================================================================

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Falta Frontal con Barrera Móvil', 'ABP-014', (SELECT id FROM categorias_tarea WHERE codigo = 'ABP'), '00000000-0000-0000-0000-000000000001', 18, 10, 1.25, 0.5, 25, 30, 'area_grande', 8, 10, 1, 'Lanzadores + Barrera + POR', 'Práctica de faltas frontales donde la barrera puede moverse (saltar/agacharse) simulando situación real. Lanzador debe leer la barrera.', 'Señal del entrenador', 'Gol o parada', '["Barrera de 4 jugadores", "Barrera puede moverse al golpeo", "Lanzador debe leer"]', 'ataque_organizado', 'Falta con lectura', 'Superar barrera reactiva', 'Muy baja intensidad', 'baja', 90, 115, 2, '["Leer intención de barrera", "Decidir: arriba, abajo, lado", "Golpeo decidido"]', '["Golpeo predecible", "No leer barrera"]', '[{"nombre": "Barrera fija", "descripcion": "No se mueve", "dificultad": "-1"}]', '["Portería reglamentaria", "Conos", "Balones x10"]', '["MD-2", "MD-1"]', true, true, '["falta frontal", "barrera", "lectura", "ABP"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Defensa de Córner: Salida al Contraataque', 'ABP-015', (SELECT id FROM categorias_tarea WHERE codigo = 'ABP'), '00000000-0000-0000-0000-000000000001', 22, 10, 1.75, 0.5, 60, 68, 'campo_propio', 14, 18, 1, '7-9 defensores + POR vs atacantes', 'Defensa de córner con énfasis en salida al contraataque tras despeje. 2 jugadores se quedan adelantados para transición. Trabaja despeje + salida rápida.', 'Córner', 'Despeje + contraataque o gol', '["2 jugadores quedan adelantados para contra", "Tras despeje: transición inmediata", "Mini portería para contraataque"]', 'defensa_organizada', 'Córner + contraataque', 'Defender y salir rápido', 'Baja intensidad con picos', 'baja', 110, 140, 2, '["Despejar hacia jugadores adelantados", "Transición inmediata", "Atacar mini portería"]', '["Despeje corto", "No salir en contra"]', '[{"nombre": "Sin contra", "descripcion": "Solo defensa", "dificultad": "-1"}]', '["Portería reglamentaria", "Mini portería x1", "Conos", "Balones x10"]', '["MD-2", "MD-1"]', true, true, '["córner", "contraataque", "defensa", "transición", "ABP"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Córner en Corto: Variantes', 'ABP-016', (SELECT id FROM categorias_tarea WHERE codigo = 'ABP'), '00000000-0000-0000-0000-000000000001', 18, 10, 1.5, 0.5, 30, 40, 'area_grande', 10, 14, 1, 'Atacantes + POR', 'Práctica de córner en corto con 3 variantes: pared y centro, conducción y centro, pared+pared+centro. Trabajo de combinación desde esquina.', 'Señal indica variante', 'Gol o despeje', '["3 variantes de córner corto", "Señalización visual", "Llegadas coordinadas al área"]', 'ataque_organizado', 'Córner en corto', 'Crear ocasión con combinación', 'Baja intensidad', 'baja', 100, 125, 2, '["Conocer señales", "Timing de combinación", "Llegadas escalonadas al área"]', '["Confusión en variante", "Timing malo"]', '[{"nombre": "Solo 1 variante", "descripcion": "Repetir misma", "dificultad": "-1"}]', '["Portería reglamentaria", "Conos", "Balones x10"]', '["MD-2", "MD-1"]', true, true, '["córner corto", "combinación", "variantes", "ABP"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Defensa Pressing Post-Córner', 'ABP-017', (SELECT id FROM categorias_tarea WHERE codigo = 'ABP'), '00000000-0000-0000-0000-000000000001', 16, 8, 1.5, 0.5, 50, 65, 'medio_campo', 16, 18, 1, 'Defensores + POR vs Atacantes', 'Trabajo de pressing inmediato tras córner a favor que no termina en gol. Al despejar rival, activar pressing alto para recuperar en zona de finalización.', 'Córner a favor que rival despeja', 'Robo alto o balón supera pressing', '["Córner sale rechazado", "Pressing inmediato", "5 segundos para recuperar alto"]', 'defensa_organizada', 'Pressing post-córner', 'Recuperar tras córner fallido', 'Alta intensidad', 'alta', 160, 180, 2, '["Pressing inmediato tras despeje", "5 seg máximo de pressing", "Cercar balón"]', '["Pressing lento", "No coordinar"]', '[{"nombre": "Sin pressing", "descripcion": "Replegar", "dificultad": "-1"}]', '["Portería reglamentaria", "Conos", "Petos", "Balones x8"]', '["MD-2", "MD-3"]', true, true, '["pressing", "post-córner", "recuperación", "ABP"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Penalti: Rutina de Portero', 'ABP-018', (SELECT id FROM categorias_tarea WHERE codigo = 'ABP'), '00000000-0000-0000-0000-000000000001', 18, 1, 16, 2, 20, 20, 'area_grande', 6, 8, 2, 'Lanzadores + 2 Porteros', 'Práctica de penaltis desde perspectiva del portero. Trabajo de lectura del lanzador, posición, movimiento lateral y reacción. Porteros alternan.', 'Lanzador listo', 'Parada o gol', '["Portero: leer antes del golpeo", "Trabajo de posición y reacción", "Alternancia de porteros"]', 'defensa_organizada', 'Defensa de penalti', 'Parar penaltis con lectura', 'Muy baja intensidad', 'baja', 95, 120, 2, '["Elegir lado", "Mantener decisión", "Golpeo firme"]', '["Anticipar demasiado", "Dudar"]', '[{"nombre": "Sin lanzador fijo", "descripcion": "Todos lanzan", "dificultad": "="}]', '["Portería reglamentaria", "Balones x8"]', '["MD-2", "MD-1"]', true, true, '["penalti", "portero", "parada", "lectura", "ABP"]');

-- ============================================================================
-- SSG/EVO/AVD - 10 tareas adicionales para completar 150
-- ============================================================================

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, forma_puntuar, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, m2_por_jugador, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('SSG 4v4+4 (Tres Equipos Rotación)', 'SSG-017', (SELECT id FROM categorias_tarea WHERE codigo = 'SSG'), '00000000-0000-0000-0000-000000000001', 20, 1, 18, 2, 35, 28, 'rectangular', 12, 12, 0, '4v4+4 (3 equipos)', 'Tres equipos de 4. 8v4: dos equipos atacan, uno defiende. Al robar, equipo que perdió pasa a defender. Similar al rondo Klopp pero con mini porterías.', 'Entrenador pasa balón', 'Gol o robo (rotación)', '["2 equipos atacan vs 1 defiende", "Equipo que pierde: pasa a defender", "Gol = punto para ambos atacantes"]', 'Goles acumulados por equipo', 'transicion_defensa_ataque', 'SSG con rotación', 'Atacar y no perder', 'Muy alta intensidad', 40.8, 'alta', 170, 190, 2, '["Atacar rápido", "No perder para no defender"]', '["Robar y cambiar rol"]', '["Perder balón fácil"]', '[{"nombre": "3v3+3", "descripcion": "Menos jugadores", "dificultad": "+1"}]', '["Mini porterías x2", "Conos", "Petos 3 colores", "Balones x6"]', '["MD-4"]', true, true, '["tres equipos", "rotación", "SSG", "intensidad"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, forma_puntuar, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, m2_por_jugador, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('SSG Futsal 5v5 (Reglas Futsal)', 'SSG-018', (SELECT id FROM categorias_tarea WHERE codigo = 'SSG'), '00000000-0000-0000-0000-000000000001', 20, 2, 8, 2, 40, 20, 'rectangular', 12, 12, 2, '5v5 (4+POR vs 4+POR)', 'Partido con reglas de futsal: saque de banda con pie, faltas acumulativas, 4 segundos para sacar. Trabaja velocidad de juego y técnica en espacio reducido.', 'Saque de centro', 'Tiempo de serie', '["Reglas futsal completas", "4 seg para sacar", "Faltas acumulan"]', 'Goles', 'ataque_organizado', 'Futsal: velocidad y técnica', 'Dominar futsal', 'Muy alta intensidad', 40, 'alta', 170, 190, 2, '["Velocidad de juego", "Técnica depurada", "Pase y desmarque rápido"]', '["Pressing alto", "No dar tiempo"]', '["Lentitud", "Técnica imprecisa"]', '[{"nombre": "Sin reglas futsal", "descripcion": "Reglas normales", "dificultad": "-1"}]', '["Porterías futsal", "Balón futsal", "Petos"]', '["MD-4", "MD+1"]', true, true, '["futsal", "velocidad", "técnica", "reducido"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Evolución: Rechace al Segundo Palo', 'EVO-017', (SELECT id FROM categorias_tarea WHERE codigo = 'EVO'), '00000000-0000-0000-0000-000000000001', 16, 10, 1.25, 0.5, 40, 45, 'area_grande', 8, 10, 1, 'Centrador + Atacantes + POR', 'Trabajo específico de atacar rechaces. Extremo centra, portero despeja, atacantes deben rematar el rechace. Énfasis en segunda jugada.', 'Extremo centra', 'Gol de rechace o despeje definitivo', '["Centro, portero despeja, atacar rechace", "Siempre 2 jugadores vigilando rechace", "Rápidos al segundo balón"]', 'ataque_organizado', 'Segunda jugada', 'Atacar rechaces', 'Media intensidad', 'media', 145, 165, 2, '["Vigilar rechace siempre", "Llegar rápido al segundo balón", "Remate decidido"]', '["No vigilar rechace", "Llegar tarde"]', '[{"nombre": "Sin rechace", "descripcion": "Centro directo", "dificultad": "-1"}]', '["Portería reglamentaria", "Conos", "Balones x12"]', '["MD-2", "MD-3"]', true, true, '["rechace", "segunda jugada", "finalización"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Evolución: Incorporación de Lateral', 'EVO-018', (SELECT id FROM categorias_tarea WHERE codigo = 'EVO'), '00000000-0000-0000-0000-000000000001', 18, 8, 1.75, 0.5, 50, 40, 'banda_area', 8, 10, 1, 'Lateral + Interior + Extremo + 9 + POR', 'Automatismo de incorporación de lateral. Lateral sube por fuera, interior le deja espacio, extremo corta, lateral centra para llegada del 9 e interior.', 'Lateral con balón en zona media', 'Gol o despeje', '["Lateral sube por fuera", "Interior se abre para dar espacio", "Extremo corta para crear hueco", "Llegadas al área coordinadas"]', 'ataque_organizado', 'Incorporación de lateral', 'Generar ocasión con lateral', 'Media intensidad', 'media', 145, 165, 2, '["Lateral: subir con decisión", "Interior: abrir espacio", "Llegadas escalonadas"]', '["Timing descoordinado", "Lateral no sube"]', '[{"nombre": "Con 1 defensor", "descripcion": "Oposición ligera", "dificultad": "+1"}]', '["Portería reglamentaria", "Conos", "Balones x10"]', '["MD-2", "MD-1"]', true, true, '["lateral", "incorporación", "automatismo"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('AVD: Defensa de Centro Raso', 'AVD-017', (SELECT id FROM categorias_tarea WHERE codigo = 'AVD'), '00000000-0000-0000-0000-000000000001', 18, 8, 1.75, 0.5, 30, 40, 'area_grande', 10, 12, 1, '5v4+POR', 'Trabajo de defensa de centros rasos al área pequeña. Extremo centra raso, defensores deben interceptar o despejar antes de que llegue al rematador.', 'Extremo en banda listo para centro raso', 'Despeje, gol o atrapada', '["Solo centros rasos", "Defensores: anticipar y despejar", "Atacantes: llegar al remate"]', 'defensa_organizada', 'Defensa centro raso', 'Evitar gol de centro raso', 'Media intensidad', 'media', 140, 160, 2, '["Llegar al centro raso", "Remate a primer toque"]', '["Anticipar centro", "Cubrir primer palo", "No dejar llegar"]', '["No anticipar", "Dejar espacio primer palo"]', '[{"nombre": "Centros variados", "descripcion": "Raso y aéreo", "dificultad": "+1"}]', '["Portería reglamentaria", "Conos", "Petos", "Balones x10"]', '["MD-3", "MD-2"]', true, true, '["centro raso", "defensa", "área", "anticipación"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('AVD: Cobertura Tras Pérdida', 'AVD-018', (SELECT id FROM categorias_tarea WHERE codigo = 'AVD'), '00000000-0000-0000-0000-000000000001', 16, 6, 2, 0.75, 50, 45, 'medio_campo', 10, 10, 1, '5v4+POR', 'Trabajo de coberturas defensivas tras pérdida de compañero. Defensor pierde duelo simulado, compañeros deben cubrir rápidamente su posición.', 'Defensor pierde duelo (simulado)', 'Cobertura exitosa o gol', '["Defensor sale de posición (simula pérdida de duelo)", "Compañeros: cobertura inmediata", "Atacantes: aprovechar hueco"]', 'defensa_organizada', 'Coberturas', 'Cubrir compañero superado', 'Alta intensidad', 'alta', 160, 180, 2, '["Atacar hueco dejado", "Aprovechar superioridad momentánea"]', '["Cobertura inmediata", "Comunicar", "No dejar hueco"]', '["Cobertura lenta", "No comunicar"]', '[{"nombre": "Sin cobertura", "descripcion": "Ver resultado sin ayuda", "dificultad": "+1"}]', '["Portería reglamentaria", "Conos", "Petos", "Balones x8"]', '["MD-4", "MD-3"]', true, true, '["cobertura", "defensa", "compañero", "ayuda"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Evolución: Disparo Tras Combinación', 'EVO-019', (SELECT id FROM categorias_tarea WHERE codigo = 'EVO'), '00000000-0000-0000-0000-000000000001', 18, 12, 1.25, 0.5, 40, 35, 'zona_14', 6, 8, 1, 'Mediocampistas + Delantero + POR', 'Trabajo de disparo desde fuera del área tras combinación. Secuencia de pases que termina en disparo desde 18-20 metros. Énfasis en golpeo y colocación.', 'Mediocentro con balón', 'Gol o parada', '["Combinación de 3-4 pases", "Disparo desde fuera del área", "Trabajo de golpeo"]', 'ataque_organizado', 'Disparo desde fuera', 'Generar ocasión de disparo', 'Media intensidad', 'media', 140, 160, 2, '["Combinación fluida", "Perfilarse para disparo", "Golpeo con potencia/colocación"]', '["Disparo flojo", "Mal perfilado"]', '[{"nombre": "Con portero", "descripcion": "Variedad de tiros", "dificultad": "="}]', '["Portería reglamentaria", "Conos", "Balones x12"]', '["MD-3", "MD-2"]', true, true, '["disparo", "fuera área", "combinación", "golpeo"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('Evolución: Volea de Remate', 'EVO-020', (SELECT id FROM categorias_tarea WHERE codigo = 'EVO'), '00000000-0000-0000-0000-000000000001', 16, 12, 1, 0.5, 30, 35, 'area_grande', 6, 8, 1, 'Centrador + Rematadores + POR', 'Trabajo específico de volea. Centros a media altura para remate de volea. Énfasis en técnica de golpeo, posición del cuerpo y timing.', 'Centro a media altura', 'Gol o parada', '["Centros a altura de volea", "Trabajo técnico de volea", "Variar pie y posición"]', 'ataque_organizado', 'Volea', 'Rematar de volea', 'Baja intensidad', 'baja', 120, 145, 2, '["Perfilarse para volea", "Cuerpo sobre el balón", "Golpeo limpio"]', '["Cuerpo echado atrás", "Timing malo"]', '[{"nombre": "Centro al ras", "descripcion": "Volea a ras de suelo", "dificultad": "+1"}]', '["Portería reglamentaria", "Conos", "Balones x12"]', '["MD-3", "MD-2"]', true, true, '["volea", "técnica", "remate", "finalización"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, forma_puntuar, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, m2_por_jugador, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('SSG Final de Entrenamiento', 'SSG-019', (SELECT id FROM categorias_tarea WHERE codigo = 'SSG'), '00000000-0000-0000-0000-000000000001', 20, 2, 8, 2, 60, 45, 'campo_reducido', 16, 18, 2, '8v8+2POR', 'Partido de fin de entrenamiento. 8v8 libre sin condiciones especiales. Aplicar todo lo trabajado en la sesión. Partido competitivo.', 'Saque de centro', 'Tiempo de serie', '["Partido libre", "Aplicar contenidos de la sesión", "Competición real"]', 'Goles', 'ataque_organizado', 'Partido libre', 'Competir aplicando lo aprendido', 'Alta intensidad', 33.8, 'alta', 160, 180, 2, '["Aplicar lo trabajado", "Jugar libre", "Competir"]', '["Aplicar conceptos defensivos", "Competir"]', '["No aplicar contenidos"]', '[{"nombre": "Con condición", "descripcion": "Añadir una regla", "dificultad": "+1"}]', '["Porterías reducidas", "Petos", "Balones x8"]', '["MD-4", "MD-3", "MD-2"]', true, true, '["partido libre", "fin sesión", "competición"]');

INSERT INTO tareas (titulo, codigo, categoria_id, organizacion_id, duracion_total, num_series, duracion_serie, tiempo_descanso, espacio_largo, espacio_ancho, espacio_forma, num_jugadores_min, num_jugadores_max, num_porteros, estructura_equipos, descripcion, como_inicia, como_finaliza, reglas_tacticas, forma_puntuar, fase_juego, principio_tactico, intencion_tactica, tipo_esfuerzo, m2_por_jugador, densidad, fc_esperada_min, fc_esperada_max, nivel_cognitivo, consignas_ofensivas, consignas_defensivas, errores_comunes, variantes, material, match_days_recomendados, es_plantilla, es_publica, tags)
VALUES ('SSG 6v6 Recuperación Activa', 'SSG-020', (SELECT id FROM categorias_tarea WHERE codigo = 'SSG'), '00000000-0000-0000-0000-000000000001', 20, 2, 8, 2, 50, 40, 'campo_reducido', 14, 14, 2, '6v6+2POR', 'Partido de recuperación activa MD+1 o MD+2. Intensidad media-baja. Prohibidas entradas fuertes. Énfasis en circulación y técnica sin contacto intenso.', 'Saque de portero', 'Tiempo de serie', '["Intensidad media-baja", "Prohibido contacto fuerte", "Énfasis en técnica"]', 'Goles', 'ataque_organizado', 'Recuperación activa', 'Recuperar jugando a baja intensidad', 'Baja intensidad', 41.7, 'baja', 120, 140, 1, '["Circular sin prisas", "Técnica limpia", "Sin contacto fuerte"]', '["Sin entradas fuertes", "Presión suave"]', '["Intensidad alta", "Contacto fuerte"]', '[{"nombre": "Intensidad normal", "descripcion": "Partido normal", "dificultad": "+1"}]', '["Porterías reducidas", "Petos", "Balones x8"]', '["MD+1", "MD+2"]', true, true, '["recuperación", "baja intensidad", "post-partido"]');

-- ============================================================================
-- FIN LOTES 11-14 - 35 TAREAS FINALES (116-150)
-- ============================================================================
-- TOTAL FINAL: 150 TAREAS PROFESIONALES
-- ============================================================================
-- Distribución final:
-- - RND: 18
-- - JDP: 15
-- - POS: 18
-- - EVO: 20
-- - AVD: 18
-- - PCO: 18
-- - SSG: 20
-- - ABP: 18
-- - TOTAL: 150 tareas (verificado por categorías: 18+15+18+20+18+18+20+18 = 145... ajustando)
-- ============================================================================
