"""
TrainingHub Pro - Models Package
Exporta todos los modelos Pydantic.
"""

from app.models.tarea import (
    FaseJuego,
    Densidad,
    NivelCognitivo,
    CategoriaTareaBase,
    CategoriaTareaResponse,
    TareaBase,
    TareaCreate,
    TareaUpdate,
    TareaResponse,
    TareaListResponse,
    TareaFiltros,
)

from app.models.sesion import (
    MatchDay,
    FaseSesion,
    EstadoSesion,
    Intensidad,
    SesionTareaBase,
    SesionTareaCreate,
    SesionTareaResponse,
    SesionBase,
    SesionCreate,
    SesionUpdate,
    SesionResponse,
    SesionListResponse,
    SesionFiltros,
    RecomendadorInput,
    RecomendadorOutput,
    TareaRecomendada,
    MatchDayConfig,
    # AI Recommender
    AITareaNueva,
    AIRecomendadorInput,
    AIRecomendadorOutput,
    AIFaseRecomendacion,
    AICargaEstimada,
)

from app.models.usuario import (
    RolUsuario,
    RolEnEquipo,
    OrganizacionBase,
    OrganizacionCreate,
    OrganizacionUpdate,
    OrganizacionResponse,
    EquipoBase,
    EquipoCreate,
    EquipoUpdate,
    EquipoResponse,
    EquipoListResponse,
    UsuarioBase,
    UsuarioCreate,
    UsuarioUpdate,
    UsuarioUpdateAdmin,
    UsuarioResponse,
    UsuarioListResponse,
    UsuarioEquipoBase,
    UsuarioEquipoCreate,
    UsuarioEquipoResponse,
    LoginRequest,
    TokenResponse,
    RefreshTokenRequest,
)

from app.models.jugador import (
    PiernaDominante,
    EstadoJugador,
    Posicion,
    JugadorBase,
    JugadorCreate,
    JugadorUpdate,
    JugadorResponse,
    JugadorListResponse,
    JugadorFiltros,
    PosicionResponse,
    PosicionListResponse,
)

__all__ = [
    # Tarea
    "FaseJuego",
    "Densidad",
    "NivelCognitivo",
    "CategoriaTareaBase",
    "CategoriaTareaResponse",
    "TareaBase",
    "TareaCreate",
    "TareaUpdate",
    "TareaResponse",
    "TareaListResponse",
    "TareaFiltros",
    # Sesion
    "MatchDay",
    "FaseSesion",
    "EstadoSesion",
    "Intensidad",
    "SesionTareaBase",
    "SesionTareaCreate",
    "SesionTareaResponse",
    "SesionBase",
    "SesionCreate",
    "SesionUpdate",
    "SesionResponse",
    "SesionListResponse",
    "SesionFiltros",
    "RecomendadorInput",
    "RecomendadorOutput",
    "TareaRecomendada",
    "MatchDayConfig",
    "AITareaNueva",
    "AIRecomendadorInput",
    "AIRecomendadorOutput",
    "AIFaseRecomendacion",
    "AICargaEstimada",
    # Usuario
    "RolUsuario",
    "RolEnEquipo",
    "OrganizacionBase",
    "OrganizacionCreate",
    "OrganizacionUpdate",
    "OrganizacionResponse",
    "EquipoBase",
    "EquipoCreate",
    "EquipoUpdate",
    "EquipoResponse",
    "EquipoListResponse",
    "UsuarioBase",
    "UsuarioCreate",
    "UsuarioUpdate",
    "UsuarioUpdateAdmin",
    "UsuarioResponse",
    "UsuarioListResponse",
    "UsuarioEquipoBase",
    "UsuarioEquipoCreate",
    "UsuarioEquipoResponse",
    "LoginRequest",
    "TokenResponse",
    "RefreshTokenRequest",
    # Jugador
    "PiernaDominante",
    "EstadoJugador",
    "Posicion",
    "JugadorBase",
    "JugadorCreate",
    "JugadorUpdate",
    "JugadorResponse",
    "JugadorListResponse",
    "JugadorFiltros",
    "PosicionResponse",
    "PosicionListResponse",
]
