"""
TrainingHub Pro - Models Package
Exporta todos los modelos Pydantic.
"""

from app.models.tarea import (
    FaseJuego,
    Densidad,
    NivelCognitivo,
    CategoriaTareaBase,
    CategoriaTareaResponse,
    TareaBase,
    TareaCreate,
    TareaUpdate,
    TareaResponse,
    TareaListResponse,
    TareaFiltros,
)

from app.models.sesion import (
    MatchDay,
    FaseSesion,
    EstadoSesion,
    Intensidad,
    SesionTareaBase,
    SesionTareaCreate,
    SesionTareaResponse,
    SesionBase,
    SesionCreate,
    SesionUpdate,
    SesionResponse,
    SesionListResponse,
    SesionFiltros,
    RecomendadorInput,
    RecomendadorOutput,
    TareaRecomendada,
    MatchDayConfig,
    # AI Recommender
    AITareaNueva,
    AIRecomendadorInput,
    AIRecomendadorOutput,
    AIFaseRecomendacion,
    AICargaEstimada,
)

from app.models.usuario import (
    RolUsuario,
    RolEnEquipo,
    OrganizacionBase,
    OrganizacionCreate,
    OrganizacionUpdate,
    OrganizacionResponse,
    EquipoBase,
    EquipoCreate,
    EquipoUpdate,
    EquipoResponse,
    EquipoListResponse,
    UsuarioBase,
    UsuarioCreate,
    UsuarioUpdate,
    UsuarioUpdateAdmin,
    UsuarioResponse,
    UsuarioListResponse,
    UsuarioEquipoBase,
    UsuarioEquipoCreate,
    UsuarioEquipoResponse,
    LoginRequest,
    TokenResponse,
    RefreshTokenRequest,
)

from app.models.jugador import (
    PiernaDominante,
    EstadoJugador,
    Posicion,
    JugadorBase,
    JugadorCreate,
    JugadorUpdate,
    JugadorResponse,
    JugadorListResponse,
    JugadorFiltros,
    PosicionResponse,
    PosicionListResponse,
)

from app.models.partido import (
    TipoCompeticion,
    LocaliaPartido,
    ResultadoPartido,
    RivalBase,
    RivalCreate,
    RivalUpdate,
    RivalResponse,
    RivalListResponse,
    PartidoBase,
    PartidoCreate,
    PartidoUpdate,
    PartidoResponse,
    PartidoListResponse,
    PartidoFiltros,
)

from app.models.microciclo import (
    EstadoMicrociclo,
    MicrocicloBase,
    MicrocicloCreate,
    MicrocicloUpdate,
    MicrocicloResponse,
    MicrocicloListResponse,
)

from app.models.rpe import (
    RPEBase,
    RPECreate,
    RPEResponse,
    RPEListResponse,
)

from app.models.convocatoria import (
    ConvocatoriaBase,
    ConvocatoriaCreate,
    ConvocatoriaUpdate,
    ConvocatoriaResponse,
    ConvocatoriaListResponse,
)

from app.models.comunicacion import (
    TipoConversacion,
    TipoMensaje,
    RolParticipante,
    PrioridadNotificacion,
    ConversacionBase,
    ConversacionCreate,
    ConversacionResponse,
    MensajeBase,
    MensajeCreate,
    MensajeResponse,
    ParticipanteResponse,
    NotificacionBase,
    NotificacionCreate,
    NotificacionResponse,
    NotificacionListResponse,
)

from app.models.ai_chat import (
    RolMensajeAI,
    AIConversacionBase,
    AIConversacionCreate,
    AIConversacionResponse,
    AIMensajeBase,
    AIMensajeCreate,
    AIMensajeResponse,
    AIChatRequest,
    AIChatResponse,
)

from app.models.knowledge_base import (
    TipoDocumentoKB,
    EstadoDocumentoKB,
    DocumentoKBBase,
    DocumentoKBCreate,
    DocumentoKBResponse,
    ChunkKBResponse,
    KBSearchRequest,
    KBSearchResult,
    KBSearchResponse,
)

__all__ = [
    # Tarea
    "FaseJuego",
    "Densidad",
    "NivelCognitivo",
    "CategoriaTareaBase",
    "CategoriaTareaResponse",
    "TareaBase",
    "TareaCreate",
    "TareaUpdate",
    "TareaResponse",
    "TareaListResponse",
    "TareaFiltros",
    # Sesion
    "MatchDay",
    "FaseSesion",
    "EstadoSesion",
    "Intensidad",
    "SesionTareaBase",
    "SesionTareaCreate",
    "SesionTareaResponse",
    "SesionBase",
    "SesionCreate",
    "SesionUpdate",
    "SesionResponse",
    "SesionListResponse",
    "SesionFiltros",
    "RecomendadorInput",
    "RecomendadorOutput",
    "TareaRecomendada",
    "MatchDayConfig",
    "AITareaNueva",
    "AIRecomendadorInput",
    "AIRecomendadorOutput",
    "AIFaseRecomendacion",
    "AICargaEstimada",
    # Usuario
    "RolUsuario",
    "RolEnEquipo",
    "OrganizacionBase",
    "OrganizacionCreate",
    "OrganizacionUpdate",
    "OrganizacionResponse",
    "EquipoBase",
    "EquipoCreate",
    "EquipoUpdate",
    "EquipoResponse",
    "EquipoListResponse",
    "UsuarioBase",
    "UsuarioCreate",
    "UsuarioUpdate",
    "UsuarioUpdateAdmin",
    "UsuarioResponse",
    "UsuarioListResponse",
    "UsuarioEquipoBase",
    "UsuarioEquipoCreate",
    "UsuarioEquipoResponse",
    "LoginRequest",
    "TokenResponse",
    "RefreshTokenRequest",
    # Jugador
    "PiernaDominante",
    "EstadoJugador",
    "Posicion",
    "JugadorBase",
    "JugadorCreate",
    "JugadorUpdate",
    "JugadorResponse",
    "JugadorListResponse",
    "JugadorFiltros",
    "PosicionResponse",
    "PosicionListResponse",
    # Partido y Rival
    "TipoCompeticion",
    "LocaliaPartido",
    "ResultadoPartido",
    "RivalBase",
    "RivalCreate",
    "RivalUpdate",
    "RivalResponse",
    "RivalListResponse",
    "PartidoBase",
    "PartidoCreate",
    "PartidoUpdate",
    "PartidoResponse",
    "PartidoListResponse",
    "PartidoFiltros",
    # Microciclo
    "EstadoMicrociclo",
    "MicrocicloBase",
    "MicrocicloCreate",
    "MicrocicloUpdate",
    "MicrocicloResponse",
    "MicrocicloListResponse",
    # RPE
    "RPEBase",
    "RPECreate",
    "RPEResponse",
    "RPEListResponse",
    # Convocatoria
    "ConvocatoriaBase",
    "ConvocatoriaCreate",
    "ConvocatoriaUpdate",
    "ConvocatoriaResponse",
    "ConvocatoriaListResponse",
    # Comunicacion
    "TipoConversacion",
    "TipoMensaje",
    "RolParticipante",
    "PrioridadNotificacion",
    "ConversacionBase",
    "ConversacionCreate",
    "ConversacionResponse",
    "MensajeBase",
    "MensajeCreate",
    "MensajeResponse",
    "ParticipanteResponse",
    "NotificacionBase",
    "NotificacionCreate",
    "NotificacionResponse",
    "NotificacionListResponse",
    # AI Chat
    "RolMensajeAI",
    "AIConversacionBase",
    "AIConversacionCreate",
    "AIConversacionResponse",
    "AIMensajeBase",
    "AIMensajeCreate",
    "AIMensajeResponse",
    "AIChatRequest",
    "AIChatResponse",
    # Knowledge Base
    "TipoDocumentoKB",
    "EstadoDocumentoKB",
    "DocumentoKBBase",
    "DocumentoKBCreate",
    "DocumentoKBResponse",
    "ChunkKBResponse",
    "KBSearchRequest",
    "KBSearchResult",
    "KBSearchResponse",
]
