#!/usr/bin/env python3
"""
TrainingHub Pro - Seed Exercises Script
Inserts ~50 high-quality template exercises into the database.
Run: python scripts/seed_exercises.py (from backend/)
  or python -m scripts.seed_exercises (from backend/)
"""

import os
import sys
from dotenv import load_dotenv

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Load .env from backend/
load_dotenv(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), '.env'))

from supabase import create_client

SUPABASE_URL = os.environ.get("SUPABASE_URL")
SUPABASE_KEY = os.environ.get("SUPABASE_SERVICE_ROLE_KEY") or os.environ.get("SUPABASE_SERVICE_KEY") or os.environ.get("SUPABASE_KEY")

SEED_TAG = "seed_v1"
# Fields that exist in exercise data but not in the DB schema
FIELDS_TO_STRIP = {"posicion_entrenador", "categoria_codigo"}


def get_supabase():
    if not SUPABASE_URL or not SUPABASE_KEY:
        print("ERROR: Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY env vars")
        sys.exit(1)
    return create_client(SUPABASE_URL, SUPABASE_KEY)


def build_categoria_map(supabase) -> dict:
    """Build a map of category code -> category ID."""
    result = supabase.table("categorias_tarea").select("id, codigo").execute()
    return {r["codigo"]: r["id"] for r in result.data}


# ============================================================
# EXERCISES DATA
# ============================================================

EXERCISES = [
    # ============ RND (Rondos) - 4 exercises ============
    {
        "titulo": "Rondo 4v2 Clasico",
        "descripcion": "Rondo basico de 4 jugadores contra 2 defensores en espacio reducido. Los 4 atacantes mantienen la posesion con toques limitados mientras los 2 defensores presionan para recuperar. Al robar, el jugador que perdio el balon pasa al centro.",
        "categoria_codigo": "RND",
        "duracion_total": 10,
        "num_series": 4,
        "duracion_serie": 2,
        "tiempo_descanso": 1,
        "espacio_largo": 8,
        "espacio_ancho": 8,
        "espacio_forma": "cuadrado",
        "num_jugadores_min": 6,
        "num_jugadores_max": 6,
        "num_porteros": 0,
        "estructura_equipos": "4v2",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Conservacion de balon",
        "densidad": "baja",
        "nivel_cognitivo": 1,
        "reglas_tecnicas": ["Maximo 2 toques", "Pase a ras de suelo"],
        "reglas_tacticas": ["Buscar amplitud en triangulos", "No devolver al mismo"],
        "consignas_ofensivas": ["Orientar el control antes de recibir", "Cuerpo abierto al juego"],
        "consignas_defensivas": ["Presion coordinada en pareja", "Cerrar lineas de pase interiores"],
        "errores_comunes": ["Control orientado pobre", "No mirar antes de recibir"],
        "variantes": ["3 toques para principiantes", "1 toque para avanzados", "Rondo 5v2 en espacio mas grande"],
        "material": ["Conos x4", "Petos x2"],
        "posicion_entrenador": "Fuera del rondo, corrigiendo orientacion corporal",
        "grafico_data": {
            "pitchType": "green",
            "elements": [
                {"type": "player", "x": 200, "y": 340, "color": "#3B82F6", "label": "1"},
                {"type": "player", "x": 300, "y": 260, "color": "#3B82F6", "label": "2"},
                {"type": "player", "x": 300, "y": 420, "color": "#3B82F6", "label": "3"},
                {"type": "player", "x": 400, "y": 340, "color": "#3B82F6", "label": "4"},
                {"type": "player", "x": 280, "y": 320, "color": "#EF4444", "label": "D1"},
                {"type": "player", "x": 320, "y": 360, "color": "#EF4444", "label": "D2"},
                {"type": "cone", "x": 180, "y": 240},
                {"type": "cone", "x": 420, "y": 240},
                {"type": "cone", "x": 180, "y": 440},
                {"type": "cone", "x": 420, "y": 440}
            ],
            "arrows": [],
            "zones": [{"x": 180, "y": 240, "width": 240, "height": 200, "color": "rgba(59,130,246,0.08)", "label": "8x8m", "shape": "rectangle"}]
        }
    },
    {
        "titulo": "Rondo 5v2 + Comodin Interior",
        "descripcion": "5 jugadores forman el exterior del rondo y 1 comodin juega dentro. 2 defensores intentan recuperar. El comodin puede moverse libremente pero solo tiene 1 toque. Los exteriores tienen 2 toques.",
        "categoria_codigo": "RND",
        "duracion_total": 12,
        "num_series": 4,
        "duracion_serie": 3,
        "tiempo_descanso": 1,
        "espacio_largo": 10,
        "espacio_ancho": 10,
        "num_jugadores_min": 8,
        "num_jugadores_max": 8,
        "num_porteros": 0,
        "estructura_equipos": "5v2+1 comodin",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Juego entre lineas",
        "densidad": "baja",
        "nivel_cognitivo": 2,
        "reglas_tecnicas": ["2 toques exteriores", "1 toque comodin", "Pase a ras de suelo"],
        "reglas_tacticas": ["Buscar pase al comodin para sumar punto", "Triangulaciones constantes"],
        "consignas_ofensivas": ["Buscar al hombre libre entre lineas", "Movimientos de apoyo"],
        "consignas_defensivas": ["Tapar linea de pase al comodin", "Pressing sincronizado"],
        "errores_comunes": ["Ignorar al comodin", "Pases predecibles"],
        "variantes": ["Comodin con 2 toques", "Doble comodin", "Sin toques limitados"],
        "material": ["Conos x4", "Petos x3"],
        "posicion_entrenador": "Lateral, enfocando en busqueda del comodin",
        "grafico_data": {
            "pitchType": "green",
            "elements": [
                {"type": "player", "x": 250, "y": 250, "color": "#3B82F6", "label": "1"},
                {"type": "player", "x": 350, "y": 250, "color": "#3B82F6", "label": "2"},
                {"type": "player", "x": 200, "y": 340, "color": "#3B82F6", "label": "3"},
                {"type": "player", "x": 400, "y": 340, "color": "#3B82F6", "label": "4"},
                {"type": "player", "x": 300, "y": 440, "color": "#3B82F6", "label": "5"},
                {"type": "player", "x": 300, "y": 340, "color": "#F59E0B", "label": "C"},
                {"type": "player", "x": 280, "y": 310, "color": "#EF4444", "label": "D1"},
                {"type": "player", "x": 320, "y": 370, "color": "#EF4444", "label": "D2"}
            ],
            "arrows": [],
            "zones": []
        }
    },
    {
        "titulo": "Rondo Posicional 3-1 en Rombo",
        "descripcion": "4 jugadores en forma de rombo (1 arriba, 2 laterales, 1 abajo) contra 1 defensor central. Se busca circular el balon cambiando orientacion. Cada 5 pases completados = 1 punto.",
        "categoria_codigo": "RND",
        "duracion_total": 8,
        "num_series": 4,
        "duracion_serie": 2,
        "tiempo_descanso": 0,
        "espacio_largo": 6,
        "espacio_ancho": 6,
        "num_jugadores_min": 5,
        "num_porteros": 0,
        "estructura_equipos": "4v1",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Salida de balon",
        "densidad": "baja",
        "nivel_cognitivo": 1,
        "reglas_tecnicas": ["2 toques", "Pase firme a ras de suelo"],
        "reglas_tacticas": ["Cambiar orientacion tras 3 pases en un lado", "No repetir pase"],
        "consignas_ofensivas": ["Control orientado", "Amplitud maxima"],
        "consignas_defensivas": ["Cerrar lineas de pase centrales"],
        "errores_comunes": ["Quedarse estatico", "Control de espaldas"],
        "variantes": ["4v2 en espacio mayor", "1 toque para avanzados"],
        "material": ["Conos x4", "Petos x1"],
        "posicion_entrenador": "Al lado del rombo",
        "grafico_data": {
            "pitchType": "green",
            "elements": [
                {"type": "player", "x": 300, "y": 260, "color": "#3B82F6", "label": "1"},
                {"type": "player", "x": 220, "y": 340, "color": "#3B82F6", "label": "2"},
                {"type": "player", "x": 380, "y": 340, "color": "#3B82F6", "label": "3"},
                {"type": "player", "x": 300, "y": 420, "color": "#3B82F6", "label": "4"},
                {"type": "player", "x": 300, "y": 340, "color": "#EF4444", "label": "D"}
            ],
            "arrows": [],
            "zones": []
        }
    },
    {
        "titulo": "Rondo Competitivo 4v4+2",
        "descripcion": "Dos equipos de 4 con 2 comodines neutrales. El equipo en posesion mas los comodines (6v4) debe completar 8 pases seguidos para ganar punto. Al perder, cambian roles.",
        "categoria_codigo": "RND",
        "duracion_total": 15,
        "num_series": 3,
        "duracion_serie": 4,
        "tiempo_descanso": 1,
        "espacio_largo": 15,
        "espacio_ancho": 15,
        "num_jugadores_min": 10,
        "num_porteros": 0,
        "estructura_equipos": "4v4+2 comodines",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Conservacion de balon",
        "densidad": "media",
        "nivel_cognitivo": 2,
        "reglas_tecnicas": ["3 toques", "Comodines 1 toque"],
        "reglas_tacticas": ["8 pases = 1 punto", "Tras perdida, pressing inmediato 3 segundos"],
        "consignas_ofensivas": ["Amplitud y profundidad", "Jugar con los comodines"],
        "consignas_defensivas": ["Pressing coordinado", "Cerrar pases a comodines"],
        "errores_comunes": ["Aglomerarse en un lado", "No usar comodines"],
        "variantes": ["10 pases para punto", "Sin limite de toques", "Zona bonus central"],
        "material": ["Conos x8", "Petos x6"],
        "posicion_entrenador": "Fuera del espacio, contando pases",
        "grafico_data": {
            "pitchType": "green",
            "elements": [
                {"type": "player", "x": 200, "y": 280, "color": "#3B82F6", "label": "1"},
                {"type": "player", "x": 350, "y": 260, "color": "#3B82F6", "label": "2"},
                {"type": "player", "x": 220, "y": 400, "color": "#3B82F6", "label": "3"},
                {"type": "player", "x": 380, "y": 400, "color": "#3B82F6", "label": "4"},
                {"type": "player", "x": 250, "y": 280, "color": "#EF4444", "label": "5"},
                {"type": "player", "x": 350, "y": 310, "color": "#EF4444", "label": "6"},
                {"type": "player", "x": 280, "y": 400, "color": "#EF4444", "label": "7"},
                {"type": "player", "x": 380, "y": 350, "color": "#EF4444", "label": "8"},
                {"type": "player", "x": 300, "y": 340, "color": "#F59E0B", "label": "C1"},
                {"type": "player", "x": 300, "y": 380, "color": "#F59E0B", "label": "C2"}
            ],
            "arrows": [],
            "zones": []
        }
    },

    # ============ JDP (Juego de Posicion) - 4 exercises ============
    {
        "titulo": "Juego de Posicion 3v3+2 en Cuadricula",
        "descripcion": "Cuadricula de 20x15m dividida en zonas. 3v3 con 2 comodines que se mueven por los laterales. El equipo en posesion busca cambios de orientacion y superioridad posicional.",
        "categoria_codigo": "JDP",
        "duracion_total": 15,
        "num_series": 3,
        "duracion_serie": 4,
        "tiempo_descanso": 1,
        "espacio_largo": 20,
        "espacio_ancho": 15,
        "num_jugadores_min": 8,
        "num_porteros": 0,
        "estructura_equipos": "3v3+2 comodines",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Progresion",
        "densidad": "media",
        "nivel_cognitivo": 3,
        "reglas_tecnicas": ["2 toques interiores", "Comodines libre"],
        "reglas_tacticas": ["Punto por cambio de orientacion con pase al tercer hombre", "Ocupar posiciones escalonadas"],
        "consignas_ofensivas": ["Desmarques de apoyo y ruptura", "Cambiar orientacion con 2 toques max"],
        "consignas_defensivas": ["Pressing en bloque", "No dejar pase al comodin"],
        "errores_comunes": ["Todos en la misma linea", "No ocupar zonas libres"],
        "variantes": ["4v4+2 en espacio mayor", "Con porterias pequenas para finalizar", "Limitacion por zonas"],
        "material": ["Conos x12", "Petos x4"],
        "posicion_entrenador": "Lateral, corrigiendo posicionamiento",
        "grafico_data": {
            "pitchType": "green",
            "elements": [
                {"type": "player", "x": 230, "y": 280, "color": "#3B82F6", "label": "1"},
                {"type": "player", "x": 300, "y": 350, "color": "#3B82F6", "label": "2"},
                {"type": "player", "x": 370, "y": 280, "color": "#3B82F6", "label": "3"},
                {"type": "player", "x": 250, "y": 350, "color": "#EF4444", "label": "4"},
                {"type": "player", "x": 330, "y": 280, "color": "#EF4444", "label": "5"},
                {"type": "player", "x": 300, "y": 400, "color": "#EF4444", "label": "6"},
                {"type": "player", "x": 200, "y": 340, "color": "#F59E0B", "label": "C1"},
                {"type": "player", "x": 400, "y": 340, "color": "#F59E0B", "label": "C2"}
            ],
            "arrows": [],
            "zones": [{"x": 190, "y": 240, "width": 220, "height": 200, "color": "rgba(59,130,246,0.06)", "label": "", "shape": "rectangle"}]
        }
    },
    {
        "titulo": "JDP 4v4+4 en Tres Zonas",
        "descripcion": "Campo dividido en 3 zonas horizontales. 4v4 en la central con 2 comodines en cada zona exterior. El objetivo es llegar de zona a zona manteniendo la posesion y creando superioridad.",
        "categoria_codigo": "JDP",
        "duracion_total": 18,
        "num_series": 3,
        "duracion_serie": 5,
        "tiempo_descanso": 1,
        "espacio_largo": 40,
        "espacio_ancho": 25,
        "num_jugadores_min": 12,
        "num_porteros": 0,
        "estructura_equipos": "4v4+4 comodines",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Salida de balon",
        "densidad": "media",
        "nivel_cognitivo": 3,
        "reglas_tecnicas": ["Zona central: 2 toques", "Zonas exteriores: libre"],
        "reglas_tacticas": ["Llegar de zona 1 a zona 3 = 1 punto", "Comodines no pueden salir de su zona"],
        "consignas_ofensivas": ["Escalonamiento", "Tercer hombre", "Pared y continuidad"],
        "consignas_defensivas": ["Pressing en zona central", "Evitar pases verticales"],
        "errores_comunes": ["No escalonarse", "Forzar pase vertical sin apoyo"],
        "variantes": ["5v5+4", "Con porterias en zonas exteriores", "1 jugador puede transitar entre zonas"],
        "material": ["Conos x16", "Petos x8"],
        "posicion_entrenador": "Lateral al centro del campo",
        "grafico_data": {
            "pitchType": "green",
            "elements": [
                {"type": "player", "x": 200, "y": 300, "color": "#3B82F6", "label": "1"},
                {"type": "player", "x": 280, "y": 340, "color": "#3B82F6", "label": "2"},
                {"type": "player", "x": 320, "y": 300, "color": "#3B82F6", "label": "3"},
                {"type": "player", "x": 380, "y": 340, "color": "#3B82F6", "label": "4"},
                {"type": "player", "x": 220, "y": 330, "color": "#EF4444", "label": "5"},
                {"type": "player", "x": 300, "y": 310, "color": "#EF4444", "label": "6"},
                {"type": "player", "x": 350, "y": 350, "color": "#EF4444", "label": "7"},
                {"type": "player", "x": 400, "y": 300, "color": "#EF4444", "label": "8"}
            ],
            "arrows": [],
            "zones": [
                {"x": 150, "y": 240, "width": 100, "height": 200, "color": "rgba(34,197,94,0.1)", "label": "Z1", "shape": "rectangle"},
                {"x": 250, "y": 240, "width": 100, "height": 200, "color": "rgba(59,130,246,0.1)", "label": "Z2", "shape": "rectangle"},
                {"x": 350, "y": 240, "width": 100, "height": 200, "color": "rgba(34,197,94,0.1)", "label": "Z3", "shape": "rectangle"}
            ]
        }
    },
    {
        "titulo": "JDP Superioridad 6v4 en Medio Campo",
        "descripcion": "6 atacantes contra 4 defensores en medio campo. Los atacantes deben progresar desde la linea de fondo hasta pasar una linea final usando principios posicionales: amplitud, profundidad, tercer hombre.",
        "categoria_codigo": "JDP",
        "duracion_total": 16,
        "num_series": 4,
        "duracion_serie": 3,
        "tiempo_descanso": 1,
        "espacio_largo": 35,
        "espacio_ancho": 30,
        "num_jugadores_min": 10,
        "num_porteros": 0,
        "estructura_equipos": "6v4",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Progresion",
        "densidad": "media",
        "nivel_cognitivo": 2,
        "reglas_tecnicas": ["Libre toques", "Pase final debe ser a ras"],
        "reglas_tacticas": ["Cruzar la linea final con pase = 1 punto", "Si defensa roba, contraataque a mini porterias"],
        "consignas_ofensivas": ["Amplitud maxima", "Tercer hombre siempre", "Progresion por banda o interior"],
        "consignas_defensivas": ["Repliegue rapido", "Cerrar pasillos interiores"],
        "errores_comunes": ["Forzar por el centro sin amplitud", "No ofrecer apoyo al portador"],
        "variantes": ["7v5 con portero", "Limitar a 3 toques", "Anadir zona de finalizacion"],
        "material": ["Conos x10", "Petos x4", "Mini porterias x2"],
        "posicion_entrenador": "Detras de la linea de los atacantes",
        "grafico_data": {
            "pitchType": "green",
            "elements": [
                {"type": "player", "x": 200, "y": 280, "color": "#3B82F6", "label": "1"},
                {"type": "player", "x": 280, "y": 300, "color": "#3B82F6", "label": "2"},
                {"type": "player", "x": 360, "y": 280, "color": "#3B82F6", "label": "3"},
                {"type": "player", "x": 200, "y": 380, "color": "#3B82F6", "label": "4"},
                {"type": "player", "x": 300, "y": 400, "color": "#3B82F6", "label": "5"},
                {"type": "player", "x": 400, "y": 380, "color": "#3B82F6", "label": "6"},
                {"type": "player", "x": 250, "y": 320, "color": "#EF4444", "label": "D1"},
                {"type": "player", "x": 350, "y": 320, "color": "#EF4444", "label": "D2"},
                {"type": "player", "x": 270, "y": 370, "color": "#EF4444", "label": "D3"},
                {"type": "player", "x": 370, "y": 370, "color": "#EF4444", "label": "D4"}
            ],
            "arrows": [],
            "zones": []
        }
    },
    {
        "titulo": "JDP Cuatro Esquinas con Pivote",
        "descripcion": "4 jugadores fijos en las esquinas de un cuadrado de 12x12m. 1 pivote central y 2 defensores dentro. Los de las esquinas y el pivote (5v2) mantienen posesion buscando cambios de orientacion por el pivote.",
        "categoria_codigo": "JDP",
        "duracion_total": 12,
        "num_series": 4,
        "duracion_serie": 3,
        "tiempo_descanso": 0,
        "espacio_largo": 12,
        "espacio_ancho": 12,
        "num_jugadores_min": 7,
        "num_porteros": 0,
        "estructura_equipos": "5v2",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Juego entre lineas",
        "densidad": "baja",
        "nivel_cognitivo": 2,
        "reglas_tecnicas": ["Esquinas: 2 toques", "Pivote: 1 toque"],
        "reglas_tacticas": ["Pase al pivote + devolucion = doble punto", "Cambio orientacion con pivote = punto"],
        "consignas_ofensivas": ["Buscar siempre al pivote primero", "Control orientado hacia donde quiero jugar"],
        "consignas_defensivas": ["Tapar linea de pase al pivote"],
        "errores_comunes": ["Pivote estatico", "No cambiar orientacion"],
        "variantes": ["6v3 con 2 pivotes", "Pivote movil (puede intercambiar)", "Sin toques al pivote"],
        "material": ["Conos x4", "Petos x3"],
        "posicion_entrenador": "Al lado del cuadrado",
        "grafico_data": {
            "pitchType": "green",
            "elements": [
                {"type": "player", "x": 230, "y": 270, "color": "#3B82F6", "label": "1"},
                {"type": "player", "x": 370, "y": 270, "color": "#3B82F6", "label": "2"},
                {"type": "player", "x": 230, "y": 410, "color": "#3B82F6", "label": "3"},
                {"type": "player", "x": 370, "y": 410, "color": "#3B82F6", "label": "4"},
                {"type": "player", "x": 300, "y": 340, "color": "#F59E0B", "label": "P"},
                {"type": "player", "x": 280, "y": 320, "color": "#EF4444", "label": "D1"},
                {"type": "player", "x": 320, "y": 360, "color": "#EF4444", "label": "D2"}
            ],
            "arrows": [],
            "zones": []
        }
    },

    # ============ POS (Posesion) - 4 exercises ============
    {
        "titulo": "Posesion 6v6+2 con Porterias de Cono",
        "descripcion": "Posesion 6v6 con 2 comodines neutrales. 4 porterias de conos (3m) en los laterales. Se marca punto al completar 6 pases Y finalizar con pase a traves de una porteria de conos.",
        "categoria_codigo": "POS",
        "duracion_total": 18,
        "num_series": 3,
        "duracion_serie": 5,
        "tiempo_descanso": 1,
        "espacio_largo": 35,
        "espacio_ancho": 25,
        "num_jugadores_min": 14,
        "num_porteros": 0,
        "estructura_equipos": "6v6+2 comodines",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Conservacion de balon",
        "densidad": "media",
        "nivel_cognitivo": 2,
        "reglas_tecnicas": ["3 toques", "Comodines 2 toques"],
        "reglas_tacticas": ["6 pases + pase por porteria = punto", "Cambio de orientacion obligatorio"],
        "consignas_ofensivas": ["Amplitud constante", "Tercer hombre para desmarque"],
        "consignas_defensivas": ["Pressing en bloque", "Basculacion rapida"],
        "errores_comunes": ["Aglomeracion", "No cambiar de orientacion"],
        "variantes": ["7v7+2", "5 pases en vez de 6", "Sin comodines"],
        "material": ["Conos x16", "Petos x8"],
        "posicion_entrenador": "Fuera del campo, lateral",
        "grafico_data": {"pitchType": "green", "elements": [], "arrows": [], "zones": []}
    },
    {
        "titulo": "Posesion 4v4+4 en Cuadrado Central",
        "descripcion": "4v4 en cuadrado central de 15x15m. 4 apoyos en los lados (1 por lado) juegan con el equipo en posesion. Objetivo: mantener posesion y buscar cambios de orientacion.",
        "categoria_codigo": "POS",
        "duracion_total": 14,
        "num_series": 3,
        "duracion_serie": 4,
        "tiempo_descanso": 1,
        "espacio_largo": 15,
        "espacio_ancho": 15,
        "num_jugadores_min": 12,
        "num_porteros": 0,
        "estructura_equipos": "4v4+4 apoyos",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Amplitud",
        "densidad": "media",
        "nivel_cognitivo": 2,
        "reglas_tecnicas": ["2 toques interiores", "Apoyos 1 toque"],
        "reglas_tacticas": ["Pase a apoyo + devolucion + cambio = punto"],
        "consignas_ofensivas": ["Moverse para recibir", "Usar apoyos para cambiar orientacion"],
        "consignas_defensivas": ["Pressing al balon", "No dejar usar apoyos"],
        "errores_comunes": ["No usar apoyos", "Todos en la misma zona"],
        "variantes": ["5v5+4", "Apoyos con 2 toques", "Zona bonus central"],
        "material": ["Conos x8", "Petos x8"],
        "posicion_entrenador": "Lateral",
        "grafico_data": {"pitchType": "green", "elements": [], "arrows": [], "zones": []}
    },
    {
        "titulo": "Posesion Progresiva con Linea Meta",
        "descripcion": "5v5 en campo de 30x20m. Cada equipo defiende una linea meta. Se gana punto al controlar el balon mas alla de la linea enemiga tras 4+ pases. Si pierden, contraataque directo.",
        "categoria_codigo": "POS",
        "duracion_total": 16,
        "num_series": 4,
        "duracion_serie": 4,
        "tiempo_descanso": 0,
        "espacio_largo": 30,
        "espacio_ancho": 20,
        "num_jugadores_min": 10,
        "num_porteros": 0,
        "estructura_equipos": "5v5",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Progresion",
        "densidad": "alta",
        "nivel_cognitivo": 2,
        "reglas_tecnicas": ["Libre toques"],
        "reglas_tacticas": ["4 pases minimo antes de cruzar linea meta", "Contraataque libre"],
        "consignas_ofensivas": ["Progresar con paciencia", "Cambiar orientacion para crear espacio"],
        "consignas_defensivas": ["Repliegue rapido", "Bloque compacto"],
        "errores_comunes": ["Forzar verticales", "No contar pases"],
        "variantes": ["6 pases minimo", "Con porterias", "Anadir comodines"],
        "material": ["Conos x8", "Petos x5"],
        "posicion_entrenador": "Lateral",
        "grafico_data": {"pitchType": "green", "elements": [], "arrows": [], "zones": []}
    },
    {
        "titulo": "Posesion 8v8 Transicional",
        "descripcion": "8v8 en medio campo con 3 segundos de pressing tras perdida. El equipo que recupera debe completar 5 pases antes de poder buscar linea de gol. Fomenta transiciones rapidas.",
        "categoria_codigo": "POS",
        "duracion_total": 20,
        "num_series": 2,
        "duracion_serie": 8,
        "tiempo_descanso": 2,
        "espacio_largo": 50,
        "espacio_ancho": 35,
        "num_jugadores_min": 16,
        "num_porteros": 0,
        "estructura_equipos": "8v8",
        "fase_juego": "transicion_defensa_ataque",
        "principio_tactico": "Ataque rapido",
        "densidad": "alta",
        "nivel_cognitivo": 3,
        "reglas_tecnicas": ["Libre toques"],
        "reglas_tacticas": ["3 seg pressing tras perdida", "5 pases tras recuperacion antes de buscar gol"],
        "consignas_ofensivas": ["Transicion rapida", "Primer pase en seguridad"],
        "consignas_defensivas": ["Pressing inmediato", "Repliegue si no se recupera en 3 seg"],
        "errores_comunes": ["No transicionar rapido", "Pressing descoordinado"],
        "variantes": ["Con porterias y porteros", "Zona de finalizacion", "10v10"],
        "material": ["Conos x12", "Petos x8"],
        "posicion_entrenador": "Lateral central",
        "grafico_data": {"pitchType": "green", "elements": [], "arrows": [], "zones": []}
    },

    # ============ EVO (Evoluciones/Oleadas) - 4 exercises ============
    {
        "titulo": "Oleadas 3v2 con Continuidad",
        "descripcion": "3 atacantes salen contra 2 defensores hacia porteria. Al finalizar (gol o perdida), 2 nuevos defensores salen desde la otra porteria con balon contra los 3 atacantes que deben replegar y defender 2v3.",
        "categoria_codigo": "EVO",
        "duracion_total": 15,
        "num_series": 3,
        "duracion_serie": 4,
        "tiempo_descanso": 1,
        "espacio_largo": 40,
        "espacio_ancho": 30,
        "num_jugadores_min": 12,
        "num_jugadores_max": 16,
        "num_porteros": 2,
        "estructura_equipos": "3v2 + oleadas",
        "fase_juego": "transicion_defensa_ataque",
        "principio_tactico": "Contraataque",
        "densidad": "alta",
        "nivel_cognitivo": 2,
        "reglas_tecnicas": ["Libre toques", "Maximo 10 segundos por ataque"],
        "reglas_tacticas": ["Oleada continua", "Tras finalizar, transicion inmediata"],
        "consignas_ofensivas": ["Velocidad en la conduccion", "2v1 en banda"],
        "consignas_defensivas": ["Temporizar en inferioridad", "Cubrir porteria"],
        "errores_comunes": ["Transicion lenta", "No cubrir el centro"],
        "variantes": ["4v3", "Con comodin permanente", "Doble porteria"],
        "material": ["Conos x8", "Petos x6"],
        "posicion_entrenador": "Lateral, a la altura de medio campo",
        "grafico_data": {
            "pitchType": "full",
            "elements": [
                {"type": "player_gk", "x": 40, "y": 340, "color": "#22C55E", "label": "GK"},
                {"type": "player_gk", "x": 1010, "y": 340, "color": "#22C55E", "label": "GK"},
                {"type": "player", "x": 300, "y": 280, "color": "#3B82F6", "label": "1"},
                {"type": "player", "x": 300, "y": 340, "color": "#3B82F6", "label": "2"},
                {"type": "player", "x": 300, "y": 400, "color": "#3B82F6", "label": "3"},
                {"type": "player", "x": 500, "y": 300, "color": "#EF4444", "label": "D1"},
                {"type": "player", "x": 500, "y": 380, "color": "#EF4444", "label": "D2"}
            ],
            "arrows": [{"from": {"x": 300, "y": 340}, "to": {"x": 450, "y": 340}, "type": "movement", "color": "#22C55E"}],
            "zones": []
        }
    },
    {
        "titulo": "Oleadas 2v1+GK Velocidad",
        "descripcion": "Oleadas rapidas de 2v1 hacia porteria. Cada oleada dura maximo 8 segundos. El defensor sale 2 metros detras de los atacantes. Trabajo de velocidad y decision en superioridad.",
        "categoria_codigo": "EVO",
        "duracion_total": 12,
        "num_series": 4,
        "duracion_serie": 3,
        "tiempo_descanso": 1,
        "espacio_largo": 30,
        "espacio_ancho": 20,
        "num_jugadores_min": 8,
        "num_porteros": 1,
        "estructura_equipos": "2v1+GK oleadas",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Finalizacion",
        "densidad": "alta",
        "nivel_cognitivo": 1,
        "reglas_tecnicas": ["Maximo 4 toques por jugador", "8 seg maximo"],
        "reglas_tacticas": ["Defensor sale retrasado", "Al finalizar, siguiente oleada"],
        "consignas_ofensivas": ["Decision rapida: pase o tiro", "Fijar al defensor"],
        "consignas_defensivas": ["Temporizar y orientar hacia banda"],
        "errores_comunes": ["Dudar en el momento de definir", "No fijar al defensor"],
        "variantes": ["3v2+GK", "Defensor sale a la par", "Con limite de zona de tiro"],
        "material": ["Conos x6", "Petos x2"],
        "posicion_entrenador": "Detras de la porteria",
        "grafico_data": {
            "pitchType": "full",
            "elements": [
                {"type": "player_gk", "x": 40, "y": 340, "color": "#22C55E", "label": "GK"},
                {"type": "player", "x": 350, "y": 310, "color": "#3B82F6", "label": "A1"},
                {"type": "player", "x": 350, "y": 370, "color": "#3B82F6", "label": "A2"},
                {"type": "player", "x": 400, "y": 340, "color": "#EF4444", "label": "D"}
            ],
            "arrows": [{"from": {"x": 350, "y": 340}, "to": {"x": 150, "y": 340}, "type": "movement", "color": "#22C55E"}],
            "zones": []
        }
    },
    {
        "titulo": "Evolucion 5v4+GK con Pressing",
        "descripcion": "5 atacantes progresan contra 4 defensores + portero. Si los defensores recuperan, contraataque a 2 mini porterias. Trabajo de ataque organizado con transicion defensiva inmediata.",
        "categoria_codigo": "EVO",
        "duracion_total": 18,
        "num_series": 3,
        "duracion_serie": 5,
        "tiempo_descanso": 1,
        "espacio_largo": 45,
        "espacio_ancho": 35,
        "num_jugadores_min": 10,
        "num_porteros": 1,
        "estructura_equipos": "5v4+GK",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Creacion de ocasiones",
        "densidad": "alta",
        "nivel_cognitivo": 3,
        "reglas_tecnicas": ["Libre toques"],
        "reglas_tacticas": ["Gol en porteria grande = 2 pts", "Gol en mini porteria = 1 pt", "Pressing tras perdida 5 seg"],
        "consignas_ofensivas": ["Amplitud y profundidad", "Tercer hombre", "Centros al area"],
        "consignas_defensivas": ["Pressing inmediato tras perdida", "Repliegue si no se recupera"],
        "errores_comunes": ["No transicionar tras perdida", "Ataque sin amplitud"],
        "variantes": ["6v5+GK", "Con fuera de juego", "Limite de tiempo: 20 seg"],
        "material": ["Conos x6", "Petos x5", "Mini porterias x2"],
        "posicion_entrenador": "Lateral a altura de 3/4 campo",
        "grafico_data": {"pitchType": "full", "elements": [], "arrows": [], "zones": []}
    },
    {
        "titulo": "Oleadas 4v4+2GK Ida y Vuelta",
        "descripcion": "4v4 con porteros en ambas porterias. Oleadas continuas: al finalizar una jugada, el portero que tiene el balon saca rapido iniciando contraataque 4v4 en la otra direccion.",
        "categoria_codigo": "EVO",
        "duracion_total": 16,
        "num_series": 2,
        "duracion_serie": 6,
        "tiempo_descanso": 2,
        "espacio_largo": 40,
        "espacio_ancho": 30,
        "num_jugadores_min": 10,
        "num_porteros": 2,
        "estructura_equipos": "4v4+2GK",
        "fase_juego": "transicion_defensa_ataque",
        "principio_tactico": "Ataque rapido",
        "densidad": "alta",
        "nivel_cognitivo": 2,
        "reglas_tecnicas": ["Libre toques", "Portero saca en 3 seg"],
        "reglas_tacticas": ["Tras gol o fuera, saque rapido del GK contrario", "No hay pausas"],
        "consignas_ofensivas": ["Transicion inmediata", "Buscar superioridad rapido"],
        "consignas_defensivas": ["Repliegue instantaneo", "Equilibrio defensivo"],
        "errores_comunes": ["Transicion lenta", "Quedarse arriba tras perder"],
        "variantes": ["5v5+2GK", "Con comodines", "Gol solo de dentro del area"],
        "material": ["Conos x4", "Petos x4"],
        "posicion_entrenador": "Lateral central",
        "grafico_data": {"pitchType": "full", "elements": [], "arrows": [], "zones": []}
    },

    # ============ AVD (Ataque vs Defensa) - 4 exercises ============
    {
        "titulo": "Ataque vs Defensa 7v7+2GK Zona Ampliada",
        "descripcion": "7v7 en 3/4 de campo con porterias reglamentarias. El equipo atacante sale con balon y debe superar la primera linea de pressing para progresar hacia gol.",
        "categoria_codigo": "AVD",
        "duracion_total": 20,
        "num_series": 2,
        "duracion_serie": 8,
        "tiempo_descanso": 2,
        "espacio_largo": 65,
        "espacio_ancho": 50,
        "num_jugadores_min": 16,
        "num_porteros": 2,
        "estructura_equipos": "7v7+2GK",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Creacion de ocasiones",
        "densidad": "alta",
        "nivel_cognitivo": 3,
        "reglas_tecnicas": ["Libre toques"],
        "reglas_tacticas": ["Fuera de juego activo", "Saque de esquina y lateral normales"],
        "consignas_ofensivas": ["Amplitud con extremos", "Tercero entrando al area", "Centros variados"],
        "consignas_defensivas": ["Linea defensiva escalonada", "Basculacion constante"],
        "errores_comunes": ["No generar amplitud", "Centros sin desmarque previo"],
        "variantes": ["8v8", "Con comodin ofensivo", "Solo gol de centro lateral"],
        "material": ["Conos x4", "Petos x7"],
        "posicion_entrenador": "Lateral a altura del area",
        "grafico_data": {"pitchType": "full", "elements": [], "arrows": [], "zones": []}
    },
    {
        "titulo": "AVD 6v4+GK Finalizacion Cruzada",
        "descripcion": "6 atacantes contra 4 defensores + portero. Los atacantes deben finalizar cruzando el centro al segundo palo. Trabajo especifico de centros y desmarques al area.",
        "categoria_codigo": "AVD",
        "duracion_total": 16,
        "num_series": 4,
        "duracion_serie": 3,
        "tiempo_descanso": 1,
        "espacio_largo": 45,
        "espacio_ancho": 40,
        "num_jugadores_min": 11,
        "num_porteros": 1,
        "estructura_equipos": "6v4+GK",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Finalizacion",
        "densidad": "alta",
        "nivel_cognitivo": 2,
        "reglas_tecnicas": ["Centro al primer o segundo toque", "Remate de primera si posible"],
        "reglas_tacticas": ["Centro cruzado = gol vale doble", "Rechace se juega"],
        "consignas_ofensivas": ["Timing de desmarque al area", "Segundo palo siempre ocupado"],
        "consignas_defensivas": ["Marcar sin perder posicion", "Cubrir segundo palo"],
        "errores_comunes": ["Llegar tarde al centro", "No ocupar segundo palo"],
        "variantes": ["Con fuera de juego", "Solo gol de cabeza", "Anadir contraataque"],
        "material": ["Conos x6", "Petos x4"],
        "posicion_entrenador": "Detras de la porteria",
        "grafico_data": {"pitchType": "full", "elements": [], "arrows": [], "zones": []}
    },
    {
        "titulo": "AVD 5v5+GK Presion Alta",
        "descripcion": "5 atacantes intentan salir jugando desde portero contra 5 defensores que presionan alto. Trabajo de salida de balon contra pressing agresivo.",
        "categoria_codigo": "AVD",
        "duracion_total": 16,
        "num_series": 4,
        "duracion_serie": 3,
        "tiempo_descanso": 1,
        "espacio_largo": 40,
        "espacio_ancho": 35,
        "num_jugadores_min": 11,
        "num_porteros": 1,
        "estructura_equipos": "5v5+GK",
        "fase_juego": "defensa_organizada",
        "principio_tactico": "Presion alta",
        "densidad": "alta",
        "nivel_cognitivo": 3,
        "reglas_tecnicas": ["Libre toques", "Portero puede jugar con los pies"],
        "reglas_tacticas": ["Si pressing recupera, tiro directo", "Salida de balon hasta medio campo = punto"],
        "consignas_ofensivas": ["Salida en corto", "3er hombre para superar pressing"],
        "consignas_defensivas": ["Pressing coordinado", "Trampas de pressing"],
        "errores_comunes": ["Pressing individual descoordinado", "Salida forzada por el centro"],
        "variantes": ["6v6+GK", "Con comodin", "2 mini porterias como objetivo de pressing"],
        "material": ["Conos x6", "Petos x5"],
        "posicion_entrenador": "Detras del equipo que presiona",
        "grafico_data": {"pitchType": "full", "elements": [], "arrows": [], "zones": []}
    },
    {
        "titulo": "AVD 8v8+2GK Partido Tactico",
        "descripcion": "Partido dirigido 8v8 en 60x45m con consignas tacticas especificas segun el principio a trabajar. El entrenador para y corrige posicionamiento.",
        "categoria_codigo": "AVD",
        "duracion_total": 25,
        "num_series": 2,
        "duracion_serie": 10,
        "tiempo_descanso": 3,
        "espacio_largo": 60,
        "espacio_ancho": 45,
        "num_jugadores_min": 18,
        "num_porteros": 2,
        "estructura_equipos": "8v8+2GK",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Juego por bandas",
        "densidad": "alta",
        "nivel_cognitivo": 3,
        "reglas_tecnicas": ["Libre toques"],
        "reglas_tacticas": ["Gol de centro = vale doble", "Fuera de juego activo"],
        "consignas_ofensivas": ["Amplitud con extremos fijados", "Desmarques de ruptura al area"],
        "consignas_defensivas": ["Basculacion colectiva", "Linea defensiva coordinada"],
        "errores_comunes": ["Perder amplitud", "No bascular"],
        "variantes": ["9v9", "Sin fuera de juego", "Solo gol tras combinacion por banda"],
        "material": ["Conos x4", "Petos x8"],
        "posicion_entrenador": "Lateral, parando juego para corregir",
        "grafico_data": {"pitchType": "full", "elements": [], "arrows": [], "zones": []}
    },

    # ============ PCO (Partido Condicionado) - 4 exercises ============
    {
        "titulo": "Partido Condicionado: 3 Zonas Obligatorias",
        "descripcion": "7v7 en campo dividido en 3 zonas horizontales. El balon debe pasar por las 3 zonas antes de poder marcar gol. Fomenta circulacion y paciencia en el juego.",
        "categoria_codigo": "PCO",
        "duracion_total": 20,
        "num_series": 2,
        "duracion_serie": 8,
        "tiempo_descanso": 2,
        "espacio_largo": 50,
        "espacio_ancho": 35,
        "num_jugadores_min": 14,
        "num_porteros": 2,
        "estructura_equipos": "7v7+2GK",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Progresion",
        "densidad": "alta",
        "nivel_cognitivo": 2,
        "reglas_tecnicas": ["Libre toques"],
        "reglas_tacticas": ["Balon debe tocar 3 zonas antes de gol", "No se puede saltar zona"],
        "consignas_ofensivas": ["Paciencia en la circulacion", "Progresar con criterio"],
        "consignas_defensivas": ["Presionar por zonas", "No dejar progresion facil"],
        "errores_comunes": ["Intentar saltar zonas", "Precipitarse en la finalizacion"],
        "variantes": ["Gol vale doble si toca 4+ jugadores", "Zona central con menos toques"],
        "material": ["Conos x12", "Petos x7"],
        "posicion_entrenador": "Lateral central",
        "grafico_data": {"pitchType": "full", "elements": [], "arrows": [], "zones": []}
    },
    {
        "titulo": "PCO: Gol Solo de Primera o Cabeza",
        "descripcion": "6v6+2GK donde los goles solo valen si son de primera (sin control previo) o de cabeza. Esto obliga a buscar centros, paredes y combinaciones rapidas.",
        "categoria_codigo": "PCO",
        "duracion_total": 18,
        "num_series": 2,
        "duracion_serie": 7,
        "tiempo_descanso": 2,
        "espacio_largo": 45,
        "espacio_ancho": 35,
        "num_jugadores_min": 14,
        "num_porteros": 2,
        "estructura_equipos": "6v6+2GK",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Finalizacion",
        "densidad": "alta",
        "nivel_cognitivo": 2,
        "reglas_tecnicas": ["Gol solo de primera o cabeza", "Libre toques en juego"],
        "reglas_tacticas": ["Centros al area incentivados", "Pared y tiro vale doble"],
        "consignas_ofensivas": ["Buscar centros", "Pases al espacio para remate de primera"],
        "consignas_defensivas": ["Cerrar lineas de tiro", "Marcar en el area"],
        "errores_comunes": ["Intentar controlar y tirar", "No ocupar area de cabeceo"],
        "variantes": ["Solo de cabeza", "Gol desde fuera del area vale triple", "Con comodines"],
        "material": ["Conos x4", "Petos x6"],
        "posicion_entrenador": "Detras de porteria",
        "grafico_data": {"pitchType": "full", "elements": [], "arrows": [], "zones": []}
    },
    {
        "titulo": "PCO: Superioridad Numerica Temporal",
        "descripcion": "5v5+2GK. Al recuperar el balon, un comodin entra en juego dando superioridad 6v5 durante 10 segundos. Si no se marca, vuelve a ser 5v5.",
        "categoria_codigo": "PCO",
        "duracion_total": 18,
        "num_series": 2,
        "duracion_serie": 7,
        "tiempo_descanso": 2,
        "espacio_largo": 40,
        "espacio_ancho": 30,
        "num_jugadores_min": 12,
        "num_porteros": 2,
        "estructura_equipos": "5v5+2GK+comodin",
        "fase_juego": "transicion_defensa_ataque",
        "principio_tactico": "Contraataque",
        "densidad": "alta",
        "nivel_cognitivo": 3,
        "reglas_tecnicas": ["Libre toques"],
        "reglas_tacticas": ["10 seg de superioridad tras recuperar", "Comodin entra por banda"],
        "consignas_ofensivas": ["Aprovechar superioridad rapido", "Buscar al comodin"],
        "consignas_defensivas": ["Repliegue urgente en inferioridad"],
        "errores_comunes": ["No aprovechar los 10 segundos", "No buscar al comodin"],
        "variantes": ["15 seg de superioridad", "2 comodines", "Sin limite de tiempo"],
        "material": ["Conos x4", "Petos x6"],
        "posicion_entrenador": "Lateral",
        "grafico_data": {"pitchType": "full", "elements": [], "arrows": [], "zones": []}
    },
    {
        "titulo": "PCO: Pressing Incentivado",
        "descripcion": "7v7+2GK con regla especial: si el equipo que pierde el balon lo recupera en 5 seg, el gol siguiente vale doble. Incentiva presion tras perdida.",
        "categoria_codigo": "PCO",
        "duracion_total": 20,
        "num_series": 2,
        "duracion_serie": 8,
        "tiempo_descanso": 2,
        "espacio_largo": 50,
        "espacio_ancho": 35,
        "num_jugadores_min": 16,
        "num_porteros": 2,
        "estructura_equipos": "7v7+2GK",
        "fase_juego": "transicion_ataque_defensa",
        "principio_tactico": "Presion tras perdida",
        "densidad": "alta",
        "nivel_cognitivo": 2,
        "reglas_tecnicas": ["Libre toques"],
        "reglas_tacticas": ["Recuperar en 5 seg = gol vale doble", "Pressing colectivo obligatorio"],
        "consignas_ofensivas": ["Transicion ofensiva rapida tras recuperar"],
        "consignas_defensivas": ["Pressing inmediato coordinado", "Si no se recupera en 5 seg, repliegue"],
        "errores_comunes": ["Pressing individual", "No transicionar tras recuperar"],
        "variantes": ["3 seg en vez de 5", "Gol vale triple", "Zona de pressing delimitada"],
        "material": ["Conos x4", "Petos x7"],
        "posicion_entrenador": "Lateral, controlando tiempo de pressing",
        "grafico_data": {"pitchType": "full", "elements": [], "arrows": [], "zones": []}
    },

    # ============ ACO (Acciones Combinadas) - 4 exercises ============
    {
        "titulo": "Combinacion Pared y Desmarque",
        "descripcion": "Ejercicio tecnico-tactico de combinaciones. Grupos de 3: pase-pared-desmarque con finalizacion a porteria. Rotacion de posiciones tras cada repeticion.",
        "categoria_codigo": "ACO",
        "duracion_total": 12,
        "num_series": 4,
        "duracion_serie": 3,
        "tiempo_descanso": 0,
        "espacio_largo": 25,
        "espacio_ancho": 20,
        "num_jugadores_min": 6,
        "num_porteros": 1,
        "estructura_equipos": "Grupos de 3",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Finalizacion",
        "densidad": "media",
        "nivel_cognitivo": 1,
        "reglas_tecnicas": ["1-2 toques", "Pase firme al pie"],
        "reglas_tacticas": ["Pared + desmarque + tiro", "Rotacion: pasador->pared->rematador"],
        "consignas_ofensivas": ["Timing del desmarque", "Pase al espacio", "Remate a puerta"],
        "consignas_defensivas": [],
        "errores_comunes": ["Desmarque prematuro", "Pared imprecisa"],
        "variantes": ["Con defensor pasivo", "Desde diferentes angulos", "Con centro al area"],
        "material": ["Conos x6"],
        "posicion_entrenador": "Detras de porteria",
        "grafico_data": {"pitchType": "full", "elements": [], "arrows": [], "zones": []}
    },
    {
        "titulo": "Circuito de Pases y Movilidad",
        "descripcion": "Circuito con 5 postas de pase donde los jugadores deben combinar y moverse a la siguiente posta. Al completar el circuito, finalizacion a porteria.",
        "categoria_codigo": "ACO",
        "duracion_total": 14,
        "num_series": 3,
        "duracion_serie": 4,
        "tiempo_descanso": 1,
        "espacio_largo": 30,
        "espacio_ancho": 25,
        "num_jugadores_min": 10,
        "num_porteros": 1,
        "estructura_equipos": "Circuito grupal",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Creacion de ocasiones",
        "densidad": "media",
        "nivel_cognitivo": 1,
        "reglas_tecnicas": ["2 toques en cada posta", "Pase al pie"],
        "reglas_tacticas": ["Completar circuito = derecho a tiro", "Moverse inmediatamente tras pasar"],
        "consignas_ofensivas": ["Pase y movimiento continuo", "Comunicacion vocal"],
        "consignas_defensivas": [],
        "errores_comunes": ["Quedarse estatico tras pasar", "No comunicar"],
        "variantes": ["Con oposicion pasiva", "3 toques", "Dos circuitos paralelos"],
        "material": ["Conos x10", "Picas x5"],
        "posicion_entrenador": "En el centro del circuito",
        "grafico_data": {"pitchType": "green", "elements": [], "arrows": [], "zones": []}
    },
    {
        "titulo": "Combinacion por Banda con Centro",
        "descripcion": "Trabajo combinativo por banda (lateral + extremo + interior) con centro al area. 3 atacantes combinan contra 1 defensor de banda, luego centran para 2 rematadores vs 2 centrales.",
        "categoria_codigo": "ACO",
        "duracion_total": 15,
        "num_series": 4,
        "duracion_serie": 3,
        "tiempo_descanso": 1,
        "espacio_largo": 40,
        "espacio_ancho": 30,
        "num_jugadores_min": 10,
        "num_porteros": 1,
        "estructura_equipos": "3v1 banda + 2v2 area",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Ataque por bandas",
        "densidad": "media",
        "nivel_cognitivo": 2,
        "reglas_tecnicas": ["Maximo 3 toques en banda", "Centro raso o aereo"],
        "reglas_tacticas": ["Combinacion obligatoria antes de centrar", "Rematadores deben hacer desmarque"],
        "consignas_ofensivas": ["Desdoblamiento de lateral", "Centro al segundo palo o retrasado"],
        "consignas_defensivas": ["Defensor de banda: temporizar", "Centrales: marca y cobertura"],
        "errores_comunes": ["Centro sin desmarque", "Timing de llegada al area"],
        "variantes": ["Por ambas bandas", "Con mas defensores", "Solo centros rasos"],
        "material": ["Conos x8", "Petos x4"],
        "posicion_entrenador": "Lateral opuesto a la banda de trabajo",
        "grafico_data": {"pitchType": "full", "elements": [], "arrows": [], "zones": []}
    },
    {
        "titulo": "Combinaciones Rapidas 3v2 al Primer Toque",
        "descripcion": "3 atacantes contra 2 defensores en espacio reducido. Los atacantes deben finalizar en maximo 4 pases, priorizando paredes y al primer toque. Oleadas continuas.",
        "categoria_codigo": "ACO",
        "duracion_total": 12,
        "num_series": 4,
        "duracion_serie": 3,
        "tiempo_descanso": 0,
        "espacio_largo": 20,
        "espacio_ancho": 15,
        "num_jugadores_min": 8,
        "num_porteros": 1,
        "estructura_equipos": "3v2+GK oleadas",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Finalizacion",
        "densidad": "alta",
        "nivel_cognitivo": 2,
        "reglas_tecnicas": ["Maximo 2 toques", "4 pases max"],
        "reglas_tacticas": ["Paredes incentivadas: gol tras pared = doble"],
        "consignas_ofensivas": ["Jugar al primer toque", "Desmarque de ruptura tras pared"],
        "consignas_defensivas": ["Interceptar lineas de pase", "No precipitarse"],
        "errores_comunes": ["Demasiados toques", "No buscar paredes"],
        "variantes": ["4v3", "Solo gol de primera", "Con limite 6 segundos"],
        "material": ["Conos x4", "Petos x2"],
        "posicion_entrenador": "Detras de porteria",
        "grafico_data": {"pitchType": "full", "elements": [], "arrows": [], "zones": []}
    },

    # ============ SSG (Futbol Reducido) - 4 exercises ============
    {
        "titulo": "SSG 4v4 con Mini Porterias",
        "descripcion": "Partido reducido 4v4 con 4 mini porterias (2 por equipo, separadas 10m). Fomenta juego de posesion, cambios de orientacion y decision de por donde atacar.",
        "categoria_codigo": "SSG",
        "duracion_total": 16,
        "num_series": 4,
        "duracion_serie": 4,
        "tiempo_descanso": 0,
        "espacio_largo": 25,
        "espacio_ancho": 20,
        "num_jugadores_min": 8,
        "num_porteros": 0,
        "estructura_equipos": "4v4",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Amplitud",
        "densidad": "alta",
        "nivel_cognitivo": 2,
        "reglas_tecnicas": ["Libre toques"],
        "reglas_tacticas": ["Gol en ambas porterias vale", "Cambio orientacion incentivado"],
        "consignas_ofensivas": ["Buscar la porteria mas desprotegida", "Amplitud y profundidad"],
        "consignas_defensivas": ["Equilibrio entre porterias", "Basculacion"],
        "errores_comunes": ["Atacar siempre a la misma porteria", "No bascular"],
        "variantes": ["5v5", "3v3 mas intenso", "Con comodines"],
        "material": ["Mini porterias x4", "Petos x4", "Conos x8"],
        "posicion_entrenador": "Fuera del campo",
        "grafico_data": {"pitchType": "green", "elements": [], "arrows": [], "zones": []}
    },
    {
        "titulo": "SSG 5v5+GK Competitivo",
        "descripcion": "Partido competitivo 5v5 con porteros en espacio de 35x25m. Reglas normales con enfasis en intensidad y transiciones. Ideal para MD-4/MD-3.",
        "categoria_codigo": "SSG",
        "duracion_total": 20,
        "num_series": 2,
        "duracion_serie": 8,
        "tiempo_descanso": 2,
        "espacio_largo": 35,
        "espacio_ancho": 25,
        "num_jugadores_min": 12,
        "num_porteros": 2,
        "estructura_equipos": "5v5+2GK",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Creacion de ocasiones",
        "densidad": "alta",
        "nivel_cognitivo": 2,
        "reglas_tecnicas": ["Libre toques"],
        "reglas_tacticas": ["Fuera de juego no aplica", "Saque lateral con el pie"],
        "consignas_ofensivas": ["Ritmo alto", "Transicion rapida"],
        "consignas_defensivas": ["Pressing intenso", "Repliegue coordinado"],
        "errores_comunes": ["Bajar intensidad", "No transicionar"],
        "variantes": ["6v6+2GK", "Con fuera de juego", "3 toques maximo"],
        "material": ["Conos x4", "Petos x5"],
        "posicion_entrenador": "Lateral",
        "grafico_data": {"pitchType": "full", "elements": [], "arrows": [], "zones": []}
    },
    {
        "titulo": "SSG 3v3 Intensivo con Rotacion",
        "descripcion": "Torneo de 3v3 en espacio reducido (15x12m) con mini porterias. Partidos de 2 minutos con rotacion de equipos. Maximo de toques: 3.",
        "categoria_codigo": "SSG",
        "duracion_total": 15,
        "num_series": 6,
        "duracion_serie": 2,
        "tiempo_descanso": 1,
        "espacio_largo": 15,
        "espacio_ancho": 12,
        "num_jugadores_min": 9,
        "num_porteros": 0,
        "estructura_equipos": "3v3 torneo",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Finalizacion",
        "densidad": "alta",
        "nivel_cognitivo": 1,
        "reglas_tecnicas": ["3 toques max"],
        "reglas_tacticas": ["2 min por partido", "Ganador se queda, perdedor rota"],
        "consignas_ofensivas": ["Decision rapida", "1v1 valiente"],
        "consignas_defensivas": ["Cerrar espacio", "No dejarse regatear"],
        "errores_comunes": ["Demasiados toques", "No tirar a puerta"],
        "variantes": ["2v2", "4v4", "Sin limite toques"],
        "material": ["Mini porterias x2", "Conos x4", "Petos x6"],
        "posicion_entrenador": "Fuera, arbitrando",
        "grafico_data": {"pitchType": "green", "elements": [], "arrows": [], "zones": []}
    },
    {
        "titulo": "SSG 6v6 Tactico con Consignas",
        "descripcion": "Partido 6v6+2GK con consignas tacticas especificas que cambian cada 5 minutos: pressing alto, bloque bajo, contraataque, posesion. Versatilidad tactica.",
        "categoria_codigo": "SSG",
        "duracion_total": 22,
        "num_series": 1,
        "duracion_serie": 20,
        "tiempo_descanso": 0,
        "espacio_largo": 45,
        "espacio_ancho": 30,
        "num_jugadores_min": 14,
        "num_porteros": 2,
        "estructura_equipos": "6v6+2GK",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Adaptacion tactica",
        "densidad": "alta",
        "nivel_cognitivo": 3,
        "reglas_tecnicas": ["Libre toques"],
        "reglas_tacticas": ["Consigna cambia cada 5 min", "Gol bajo consigna correcta = doble"],
        "consignas_ofensivas": ["Adaptarse a cada consigna", "Comunicar el cambio"],
        "consignas_defensivas": ["Pressing o bloque segun consigna"],
        "errores_comunes": ["No adaptarse al cambio de consigna", "Falta de comunicacion"],
        "variantes": ["Cambio cada 3 min", "Los jugadores eligen la consigna"],
        "material": ["Conos x4", "Petos x6"],
        "posicion_entrenador": "Lateral, anunciando consignas",
        "grafico_data": {"pitchType": "full", "elements": [], "arrows": [], "zones": []}
    },

    # ============ ABP (Balon Parado) - 4 exercises ============
    {
        "titulo": "Corner Ofensivo: Variantes Corto/Largo",
        "descripcion": "Ensayo de saques de esquina con 3 variantes: corner largo al primer palo, corner corto con combinacion, y corner al segundo palo con blocaje. 8 atacantes vs 6 defensores.",
        "categoria_codigo": "ABP",
        "duracion_total": 15,
        "num_series": 5,
        "duracion_serie": 2,
        "tiempo_descanso": 1,
        "espacio_largo": 40,
        "espacio_ancho": 40,
        "num_jugadores_min": 15,
        "num_porteros": 1,
        "estructura_equipos": "8v6+GK",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Balon parado ofensivo",
        "densidad": "baja",
        "nivel_cognitivo": 2,
        "reglas_tecnicas": ["Corner al primer palo: con efecto", "Corner corto: pase firme"],
        "reglas_tacticas": ["Senal visual para elegir variante", "Movimientos de arrastre"],
        "consignas_ofensivas": ["Timing de carrera", "Atacar zonas no jugadores"],
        "consignas_defensivas": ["Marca zonal en zona de peligro"],
        "errores_comunes": ["Salir antes de la senal", "No atacar el balon"],
        "variantes": ["Anadir variante de saque rapido", "Cambiar de esquina", "Con falta lateral"],
        "material": ["Conos x4"],
        "posicion_entrenador": "Detras de porteria",
        "grafico_data": {"pitchType": "full", "elements": [], "arrows": [], "zones": []}
    },
    {
        "titulo": "Falta Lateral Ofensiva",
        "descripcion": "Ensayo de faltas laterales desde 25-30m de porteria. Variantes: disparo directo, centro al area, y combinacion corta. Trabajo de posicionamiento de la barrera y desmarques.",
        "categoria_codigo": "ABP",
        "duracion_total": 12,
        "num_series": 4,
        "duracion_serie": 3,
        "tiempo_descanso": 0,
        "espacio_largo": 35,
        "espacio_ancho": 40,
        "num_jugadores_min": 12,
        "num_porteros": 1,
        "estructura_equipos": "7v5+GK",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Balon parado ofensivo",
        "densidad": "baja",
        "nivel_cognitivo": 2,
        "reglas_tecnicas": ["Golpeo con empeine o interior", "Centro tenso al area"],
        "reglas_tacticas": ["2 variantes por cada falta", "Senal de ejecucion clara"],
        "consignas_ofensivas": ["Movimientos de arrastre", "Ocupar zonas clave"],
        "consignas_defensivas": ["Barrera bien posicionada", "Marca en zona"],
        "errores_comunes": ["Ejecucion predecible", "No ocupar el segundo palo"],
        "variantes": ["Desde diferentes distancias", "Con barrera de 4 o 5", "Doble toque"],
        "material": ["Conos x4", "Maniquis x3"],
        "posicion_entrenador": "Al lado del ejecutor",
        "grafico_data": {"pitchType": "full", "elements": [], "arrows": [], "zones": []}
    },
    {
        "titulo": "Defensa de Corner: Marca Zonal",
        "descripcion": "Trabajo defensivo de saques de esquina con sistema zonal. Asignacion de zonas, responsabilidades de marca y despeje. 6 defensores + GK vs 7 atacantes.",
        "categoria_codigo": "ABP",
        "duracion_total": 14,
        "num_series": 5,
        "duracion_serie": 2,
        "tiempo_descanso": 1,
        "espacio_largo": 40,
        "espacio_ancho": 40,
        "num_jugadores_min": 14,
        "num_porteros": 1,
        "estructura_equipos": "7v6+GK",
        "fase_juego": "defensa_organizada",
        "principio_tactico": "Balon parado defensivo",
        "densidad": "baja",
        "nivel_cognitivo": 2,
        "reglas_tecnicas": ["Despeje lejos de porteria", "Atacar el balon con agresividad"],
        "reglas_tacticas": ["Zona asignada inamovible", "Portero manda: 'fuera!' o 'mia!'"],
        "consignas_ofensivas": ["Variar tipo de corner"],
        "consignas_defensivas": ["Cada zona cubierta", "Ganar posicion al atacante", "Primer despeje contundente"],
        "errores_comunes": ["Abandonar zona por seguir atacante", "No atacar el balon aereo"],
        "variantes": ["Corner corto", "Con marca mixta (zonal + individual)", "Contraataque tras despeje"],
        "material": ["Conos x6"],
        "posicion_entrenador": "Dentro del area, corrigiendo posiciones",
        "grafico_data": {"pitchType": "full", "elements": [], "arrows": [], "zones": []}
    },
    {
        "titulo": "ABP Penaltis y Faltas Directas",
        "descripcion": "Sesion de practica de penaltis y faltas directas. Cada jugador ejecuta 3 penaltis y 2 faltas. Trabajo psicologico: presion del grupo, rutina pre-lanzamiento.",
        "categoria_codigo": "ABP",
        "duracion_total": 15,
        "num_series": 1,
        "duracion_serie": 15,
        "tiempo_descanso": 0,
        "espacio_largo": 25,
        "espacio_ancho": 16,
        "num_jugadores_min": 8,
        "num_porteros": 2,
        "estructura_equipos": "Individual + GK",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Balon parado ofensivo",
        "densidad": "baja",
        "nivel_cognitivo": 1,
        "reglas_tecnicas": ["Carrera firme", "Golpeo seguro a un lado"],
        "reglas_tacticas": ["Rutina pre-lanzamiento obligatoria", "El grupo observa y apoya/presiona"],
        "consignas_ofensivas": ["Decidir lado antes de poner el balon", "No cambiar decision"],
        "consignas_defensivas": ["GK: analizar tendencia del tirador"],
        "errores_comunes": ["Cambiar de idea en la carrera", "No tener rutina"],
        "variantes": ["Penaltis bajo presion (el equipo pierde si falla 2)", "Desde diferentes angulos"],
        "material": ["Conos x2"],
        "posicion_entrenador": "Detras de la porteria, analizando tecnica",
        "grafico_data": {"pitchType": "full", "elements": [], "arrows": [], "zones": []}
    },

    # ============ GYM (Fuerza/Gimnasio) - 4 exercises ============
    {
        "titulo": "Sentadilla Goblet con Kettlebell",
        "descripcion": "Sentadilla con kettlebell sostenida a la altura del pecho. Trabajo de fuerza de tren inferior con enfasis en cuadriceps, gluteos e isquiotibiales. Control excentrico de 3 seg bajando.",
        "categoria_codigo": "GYM",
        "duracion_total": 12,
        "num_series": 4,
        "duracion_serie": 2,
        "tiempo_descanso": 1,
        "espacio_largo": 0,
        "espacio_ancho": 0,
        "espacio_forma": "gimnasio",
        "num_jugadores_min": 1,
        "num_jugadores_max": 4,
        "num_porteros": 0,
        "estructura_equipos": "Individual",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Preparacion fisica",
        "densidad": "media",
        "nivel_cognitivo": 1,
        "reglas_tecnicas": ["Rodillas alineadas con pies", "Espalda neutra", "Control excentrico 3 seg"],
        "reglas_tacticas": [],
        "consignas_ofensivas": ["Profundidad completa", "Activar core en todo momento"],
        "consignas_defensivas": [],
        "errores_comunes": ["Rodillas hacia dentro", "Perder postura lumbar", "Rebotar abajo"],
        "variantes": ["Con barra", "Sentadilla bulgara", "Sentadilla frontal"],
        "material": ["Kettlebell"],
        "posicion_entrenador": "Al lado, corrigiendo tecnica",
        "es_complementaria": True,
        "grupo_muscular": ["cuadriceps", "gluteos", "isquiotibiales"],
        "equipamiento": ["kettlebell"],
        "tipo_contraccion": "concentrica",
        "zona_cuerpo": "tren_inferior",
        "objetivo_gym": "fuerza_maxima",
        "series_repeticiones": {"series": 4, "repeticiones": "8-10", "descanso_seg": 90, "porcentaje_rm": 70},
        "grafico_data": {"pitchType": "green", "elements": [], "arrows": [], "zones": []}
    },
    {
        "titulo": "Hip Thrust con Barra",
        "descripcion": "Empuje de cadera con barra olimpica apoyando espalda alta en banco. Enfoque en gluteos y extension de cadera completa. Pausa de 1 seg arriba.",
        "categoria_codigo": "GYM",
        "duracion_total": 12,
        "num_series": 4,
        "duracion_serie": 2,
        "tiempo_descanso": 1,
        "espacio_largo": 0,
        "espacio_ancho": 0,
        "espacio_forma": "gimnasio",
        "num_jugadores_min": 1,
        "num_jugadores_max": 4,
        "num_porteros": 0,
        "estructura_equipos": "Individual",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Preparacion fisica",
        "densidad": "media",
        "nivel_cognitivo": 1,
        "reglas_tecnicas": ["Extension completa de cadera", "Pausa 1 seg arriba", "No hiperextender lumbar"],
        "reglas_tacticas": [],
        "consignas_ofensivas": ["Apretar gluteos arriba", "Barbilla al pecho"],
        "consignas_defensivas": [],
        "errores_comunes": ["Hiperextension lumbar", "No llegar a extension completa"],
        "variantes": ["Con banda elastica en rodillas", "Unilateral", "Con mancuerna"],
        "material": ["Barra olimpica", "Banco"],
        "posicion_entrenador": "Lateral, supervisando tecnica",
        "es_complementaria": True,
        "grupo_muscular": ["gluteos", "isquiotibiales"],
        "equipamiento": ["barra olimpica", "banco"],
        "tipo_contraccion": "concentrica",
        "zona_cuerpo": "tren_inferior",
        "objetivo_gym": "fuerza_maxima",
        "series_repeticiones": {"series": 4, "repeticiones": "10-12", "descanso_seg": 90, "porcentaje_rm": 65},
        "grafico_data": {"pitchType": "green", "elements": [], "arrows": [], "zones": []}
    },
    {
        "titulo": "Peso Muerto Rumano",
        "descripcion": "Peso muerto rumano con barra. Enfasis en elongacion de isquiotibiales y control excentrico. Fundamental para prevencion de lesiones en isquiotibiales.",
        "categoria_codigo": "GYM",
        "duracion_total": 12,
        "num_series": 3,
        "duracion_serie": 3,
        "tiempo_descanso": 1,
        "espacio_largo": 0,
        "espacio_ancho": 0,
        "espacio_forma": "gimnasio",
        "num_jugadores_min": 1,
        "num_jugadores_max": 4,
        "num_porteros": 0,
        "estructura_equipos": "Individual",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Preparacion fisica",
        "densidad": "media",
        "nivel_cognitivo": 1,
        "reglas_tecnicas": ["Barra pegada al cuerpo", "Rodillas ligeramente flexionadas", "Control excentrico 3 seg"],
        "reglas_tacticas": [],
        "consignas_ofensivas": ["Sentir elongacion en isquios", "Espalda neutra siempre"],
        "consignas_defensivas": [],
        "errores_comunes": ["Redondear espalda", "Doblar demasiado rodillas", "Barra lejos del cuerpo"],
        "variantes": ["Con mancuernas", "Unilateral", "Con kettlebell"],
        "material": ["Barra olimpica"],
        "posicion_entrenador": "Lateral, vigilando postura",
        "es_complementaria": True,
        "grupo_muscular": ["isquiotibiales", "gluteos", "lumbar"],
        "equipamiento": ["barra olimpica"],
        "tipo_contraccion": "excentrica",
        "zona_cuerpo": "tren_inferior",
        "objetivo_gym": "fuerza_maxima",
        "series_repeticiones": {"series": 3, "repeticiones": "8-10", "descanso_seg": 120, "porcentaje_rm": 65},
        "grafico_data": {"pitchType": "green", "elements": [], "arrows": [], "zones": []}
    },
    {
        "titulo": "Circuito Core Funcional",
        "descripcion": "Circuito de 4 ejercicios de core: plancha frontal (30s), plancha lateral (20s/lado), dead bug (10 rep), pallof press (10 rep/lado). 3 rondas.",
        "categoria_codigo": "GYM",
        "duracion_total": 15,
        "num_series": 3,
        "duracion_serie": 4,
        "tiempo_descanso": 1,
        "espacio_largo": 0,
        "espacio_ancho": 0,
        "espacio_forma": "gimnasio",
        "num_jugadores_min": 1,
        "num_jugadores_max": 8,
        "num_porteros": 0,
        "estructura_equipos": "Individual",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Preparacion fisica",
        "densidad": "media",
        "nivel_cognitivo": 1,
        "reglas_tecnicas": ["Plancha: cuerpo recto, no subir caderas", "Dead bug: lumbar pegada al suelo"],
        "reglas_tacticas": [],
        "consignas_ofensivas": ["Respiracion controlada", "Activacion profunda del core"],
        "consignas_defensivas": [],
        "errores_comunes": ["Subir caderas en plancha", "Arquear lumbar en dead bug", "Rotar en pallof press"],
        "variantes": ["Anadir ejercicio de rotacion", "Aumentar tiempos", "Con peso extra"],
        "material": ["Esterilla", "Banda elastica", "Polea"],
        "posicion_entrenador": "Recorriendo el grupo",
        "es_complementaria": True,
        "grupo_muscular": ["core", "abdominales", "oblicuos"],
        "equipamiento": ["esterilla", "banda elastica"],
        "tipo_contraccion": "isometrica",
        "zona_cuerpo": "core",
        "objetivo_gym": "resistencia_muscular",
        "series_repeticiones": {"series": 3, "repeticiones": "30s/10 rep", "descanso_seg": 60},
        "grafico_data": {"pitchType": "green", "elements": [], "arrows": [], "zones": []}
    },

    # ============ PRV (Prevencion) - 2 exercises ============
    {
        "titulo": "Nordic Hamstring Curl",
        "descripcion": "Ejercicio excentrico de isquiotibiales para prevencion de lesiones. El jugador se arrodilla y baja el cuerpo controladamente mientras un companero sujeta los tobillos. Bajar lo mas lento posible.",
        "categoria_codigo": "PRV",
        "duracion_total": 8,
        "num_series": 3,
        "duracion_serie": 2,
        "tiempo_descanso": 1,
        "espacio_largo": 0,
        "espacio_ancho": 0,
        "espacio_forma": "campo",
        "num_jugadores_min": 2,
        "num_jugadores_max": 20,
        "num_porteros": 0,
        "estructura_equipos": "Parejas",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Preparacion fisica",
        "densidad": "baja",
        "nivel_cognitivo": 1,
        "reglas_tecnicas": ["Bajar lo mas lento posible", "Caderas extendidas", "No flexionar cadera al bajar"],
        "reglas_tacticas": [],
        "consignas_ofensivas": ["Control total de la bajada", "Usar manos para frenar al final"],
        "consignas_defensivas": [],
        "errores_comunes": ["Flexionar cadera", "Dejarse caer sin control", "No llegar a rango completo"],
        "variantes": ["Con banda para asistir", "Excentrico solo (sin concentrico)", "Con carga adicional"],
        "material": ["Esterilla"],
        "posicion_entrenador": "Supervisando tecnica de parejas",
        "es_complementaria": True,
        "grupo_muscular": ["isquiotibiales"],
        "equipamiento": ["esterilla"],
        "tipo_contraccion": "excentrica",
        "zona_cuerpo": "tren_inferior",
        "objetivo_gym": "fuerza_maxima",
        "series_repeticiones": {"series": 3, "repeticiones": "5-8", "descanso_seg": 90},
        "grafico_data": {"pitchType": "green", "elements": [], "arrows": [], "zones": []}
    },
    {
        "titulo": "Protocolo Copenhagen Aductores",
        "descripcion": "Ejercicio de fortalecimiento de aductores en pareja. Un jugador en plancha lateral con la pierna superior apoyada en el hombro del companero. Subir y bajar la pierna inferior controladamente.",
        "categoria_codigo": "PRV",
        "duracion_total": 8,
        "num_series": 3,
        "duracion_serie": 2,
        "tiempo_descanso": 1,
        "espacio_largo": 0,
        "espacio_ancho": 0,
        "espacio_forma": "campo",
        "num_jugadores_min": 2,
        "num_jugadores_max": 20,
        "num_porteros": 0,
        "estructura_equipos": "Parejas",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Preparacion fisica",
        "densidad": "baja",
        "nivel_cognitivo": 1,
        "reglas_tecnicas": ["Cuerpo recto en plancha", "Control del movimiento", "No rotar pelvis"],
        "reglas_tacticas": [],
        "consignas_ofensivas": ["Apretar aductores", "Mantener alineacion corporal"],
        "consignas_defensivas": [],
        "errores_comunes": ["Rotacion de pelvis", "Perder alineacion", "Velocidad excesiva"],
        "variantes": ["Con rodilla flexionada (mas facil)", "Isometrico estatico", "Con banda elastica"],
        "material": ["Esterilla"],
        "posicion_entrenador": "Recorriendo parejas",
        "es_complementaria": True,
        "grupo_muscular": ["aductores", "core"],
        "equipamiento": ["esterilla"],
        "tipo_contraccion": "concentrica",
        "zona_cuerpo": "tren_inferior",
        "objetivo_gym": "fuerza_maxima",
        "series_repeticiones": {"series": 3, "repeticiones": "8-10/lado", "descanso_seg": 60},
        "grafico_data": {"pitchType": "green", "elements": [], "arrows": [], "zones": []}
    },

    # ============ MOV (Movilidad) - 2 exercises ============
    {
        "titulo": "Rutina Movilidad Dinamica Pre-Entrenamiento",
        "descripcion": "Circuito de movilidad dinamica: estocadas con rotacion, inchworms, opening the gate, world's greatest stretch, leg swings. 10 metros ida y vuelta por ejercicio.",
        "categoria_codigo": "MOV",
        "duracion_total": 10,
        "num_series": 2,
        "duracion_serie": 5,
        "tiempo_descanso": 0,
        "espacio_largo": 10,
        "espacio_ancho": 5,
        "espacio_forma": "rectangular",
        "num_jugadores_min": 4,
        "num_jugadores_max": 24,
        "num_porteros": 0,
        "estructura_equipos": "Grupal",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Preparacion fisica",
        "densidad": "baja",
        "nivel_cognitivo": 1,
        "reglas_tecnicas": ["Movimientos amplios y controlados", "No rebotar", "Respiracion fluida"],
        "reglas_tacticas": [],
        "consignas_ofensivas": ["Rango completo de movimiento", "Progresion gradual"],
        "consignas_defensivas": [],
        "errores_comunes": ["Movimientos balisticos", "Acortar rango", "No activar musculatura"],
        "variantes": ["Anadir bandas", "Mas tiempo por ejercicio", "Variante con balon"],
        "material": ["Conos x4"],
        "posicion_entrenador": "Al frente del grupo, demostrando",
        "es_complementaria": True,
        "grupo_muscular": ["cadera", "isquiotibiales", "cuadriceps", "columna"],
        "equipamiento": [],
        "tipo_contraccion": "concentrica",
        "zona_cuerpo": "full_body",
        "objetivo_gym": "movilidad",
        "grafico_data": {"pitchType": "green", "elements": [], "arrows": [], "zones": []}
    },
    {
        "titulo": "Movilidad de Cadera y Tobillo",
        "descripcion": "Rutina especifica de movilidad para cadera y tobillo: 90/90, frog stretch, pigeon stretch, dorsiflexion en pared, sentadilla profunda con pausa. 30 seg por posicion.",
        "categoria_codigo": "MOV",
        "duracion_total": 8,
        "num_series": 2,
        "duracion_serie": 4,
        "tiempo_descanso": 0,
        "espacio_largo": 0,
        "espacio_ancho": 0,
        "espacio_forma": "campo",
        "num_jugadores_min": 1,
        "num_jugadores_max": 24,
        "num_porteros": 0,
        "estructura_equipos": "Individual",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Preparacion fisica",
        "densidad": "baja",
        "nivel_cognitivo": 1,
        "reglas_tecnicas": ["Mantener posicion 30 seg", "Respirar profundamente", "No forzar dolor"],
        "reglas_tacticas": [],
        "consignas_ofensivas": ["Relajar en la posicion", "Progresion gradual"],
        "consignas_defensivas": [],
        "errores_comunes": ["Forzar rango con dolor", "No respirar", "Rebotar"],
        "variantes": ["Con foam roller", "Con banda para traccion", "Secuencia mas larga"],
        "material": ["Esterilla"],
        "posicion_entrenador": "Demostrando cada posicion",
        "es_complementaria": True,
        "grupo_muscular": ["cadera", "tobillo", "gluteos"],
        "equipamiento": ["esterilla"],
        "tipo_contraccion": "isometrica",
        "zona_cuerpo": "tren_inferior",
        "objetivo_gym": "movilidad",
        "grafico_data": {"pitchType": "green", "elements": [], "arrows": [], "zones": []}
    },

    # ============ RCF (Recuperacion Fisica) - 2 exercises ============
    {
        "titulo": "Vuelta a la Calma con Foam Roller",
        "descripcion": "Sesion de auto-masaje con foam roller para recuperacion post-entrenamiento. Trabajo de cuadriceps, isquiotibiales, gemelos, IT band, gluteos y dorsal. 60 seg por grupo muscular.",
        "categoria_codigo": "RCF",
        "duracion_total": 10,
        "num_series": 1,
        "duracion_serie": 10,
        "tiempo_descanso": 0,
        "espacio_largo": 0,
        "espacio_ancho": 0,
        "espacio_forma": "campo",
        "num_jugadores_min": 1,
        "num_jugadores_max": 24,
        "num_porteros": 0,
        "estructura_equipos": "Individual",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Preparacion fisica",
        "densidad": "baja",
        "nivel_cognitivo": 1,
        "reglas_tecnicas": ["Rodar lento sobre el musculo", "Pausar en puntos de tension", "No rodar sobre articulaciones"],
        "reglas_tacticas": [],
        "consignas_ofensivas": ["60 seg por grupo muscular", "Respirar y relajar"],
        "consignas_defensivas": [],
        "errores_comunes": ["Rodar demasiado rapido", "Saltarse zonas dolorosas", "Rodar sobre hueso"],
        "variantes": ["Con pelota de lacrosse para puntos especificos", "Con roller vibratorio"],
        "material": ["Foam roller"],
        "posicion_entrenador": "Guiando la secuencia",
        "es_complementaria": True,
        "grupo_muscular": ["cuadriceps", "isquiotibiales", "gemelos", "gluteos", "dorsal"],
        "equipamiento": ["foam roller"],
        "tipo_contraccion": "concentrica",
        "zona_cuerpo": "full_body",
        "objetivo_gym": "recuperacion",
        "grafico_data": {"pitchType": "green", "elements": [], "arrows": [], "zones": []}
    },
    {
        "titulo": "Carrera Continua Regenerativa + Estiramientos",
        "descripcion": "Trote suave de 8 minutos a ritmo conversacional seguido de rutina de estiramientos estaticos de 7 minutos. Ideal para dia de recuperacion (MD+1).",
        "categoria_codigo": "RCF",
        "duracion_total": 15,
        "num_series": 1,
        "duracion_serie": 15,
        "tiempo_descanso": 0,
        "espacio_largo": 0,
        "espacio_ancho": 0,
        "espacio_forma": "campo",
        "num_jugadores_min": 4,
        "num_jugadores_max": 24,
        "num_porteros": 0,
        "estructura_equipos": "Grupal",
        "fase_juego": "ataque_organizado",
        "principio_tactico": "Preparacion fisica",
        "densidad": "baja",
        "nivel_cognitivo": 1,
        "reglas_tecnicas": ["Ritmo conversacional", "FC max 60%", "Estiramientos 20-30 seg por posicion"],
        "reglas_tacticas": [],
        "consignas_ofensivas": ["No acelerar", "Respiracion nasal si posible"],
        "consignas_defensivas": [],
        "errores_comunes": ["Correr demasiado rapido", "Estirar con rebotes", "Acortar tiempo"],
        "variantes": ["Con bicicleta en vez de trote", "Yoga basico en vez de estiramientos"],
        "material": [],
        "posicion_entrenador": "Con el grupo, marcando ritmo",
        "es_complementaria": True,
        "grupo_muscular": ["general", "cardiovascular"],
        "equipamiento": [],
        "tipo_contraccion": "concentrica",
        "zona_cuerpo": "full_body",
        "objetivo_gym": "recuperacion",
        "grafico_data": {"pitchType": "green", "elements": [], "arrows": [], "zones": []}
    },
]


def seed():
    supabase = get_supabase()

    # Idempotency check: if any seed exercise already exists, skip
    existing = supabase.table("tareas").select("id").eq("es_plantilla", True).eq("titulo", "Rondo 4v2 Clasico").limit(1).execute()
    if existing.data:
        print(f"Seed exercises already exist. Skipping.")
        return

    # Get a valid organizacion_id (required NOT NULL column)
    org_result = supabase.table("organizaciones").select("id").limit(1).execute()
    if not org_result.data:
        print("ERROR: No organizations found. Create one first.")
        sys.exit(1)
    org_id = org_result.data[0]["id"]
    print(f"Using organizacion_id: {org_id}")

    # Build category map
    cat_map = build_categoria_map(supabase)
    if not cat_map:
        print("ERROR: No categories found in categorias_tarea table. Run migrations first.")
        sys.exit(1)

    print(f"Found {len(cat_map)} categories: {list(cat_map.keys())}")
    print(f"Inserting {len(EXERCISES)} exercises...\n")

    inserted = 0
    skipped = 0

    for ex in EXERCISES:
        # Pop the helper field before building payload
        cat_code = ex.pop("categoria_codigo")
        cat_id = cat_map.get(cat_code)

        if not cat_id:
            print(f"  WARNING: Category '{cat_code}' not found in DB, skipping: {ex['titulo']}")
            skipped += 1
            # Restore so repeated runs work if needed (though idempotency handles this)
            ex["categoria_codigo"] = cat_code
            continue

        # Remove fields not in DB schema
        payload = {
            k: v for k, v in ex.items()
            if k not in FIELDS_TO_STRIP
        }
        payload.update({
            "categoria_id": cat_id,
            "organizacion_id": org_id,
            "es_plantilla": True,
            "es_publica": True,
            "tags": [SEED_TAG, cat_code.lower()],
        })

        try:
            result = supabase.table("tareas").insert(payload).execute()
            if result.data:
                inserted += 1
                print(f"  [{cat_code}] {ex['titulo']}")
            else:
                print(f"  WARNING: No data returned for '{ex['titulo']}'")
                skipped += 1
        except Exception as e:
            print(f"  ERROR inserting '{ex['titulo']}': {e}")
            skipped += 1
        finally:
            # Restore categoria_codigo in case dict is reused
            ex["categoria_codigo"] = cat_code

    print(f"\nDone! Inserted {inserted}/{len(EXERCISES)} exercises. Skipped: {skipped}.")


if __name__ == "__main__":
    seed()
