/** Erratas y formas canónicas del fútbol / metodología. Solo entradas unívocas. */

export const WORD_CORRECTIONS: Record<string, string> = {
  // ── Ortografía general frecuente ──────────────────────────────────────────
  tambien: 'también',
  despues: 'después',
  ademas: 'además',
  asi: 'así',
  aqui: 'aquí',
  alli: 'allí',
  alla: 'allá',
  rapido: 'rápido',
  rapida: 'rápida',
  facil: 'fácil',
  dificil: 'difícil',
  minimo: 'mínimo',
  maximo: 'máximo',
  ultimo: 'último',
  ultima: 'última',
  proximimo: 'próximo',
  proximo: 'próximo',
  proxima: 'próxima',
  tecnico: 'técnico',
  tecnica: 'técnica',
  tecnicos: 'técnicos',
  tecnicas: 'técnicas',
  tactico: 'táctico',
  tactica: 'táctica',
  tacticos: 'tácticos',
  tacticas: 'tácticas',
  fisico: 'físico',
  fisica: 'física',
  fisicos: 'físicos',
  fisicas: 'físicas',
  psicologico: 'psicológico',
  psicologica: 'psicológica',
  metodo: 'método',
  metodologia: 'metodología',
  analisis: 'análisis',
  periodo: 'período',
  dias: 'días',
  minuto: 'minuto',
  minutos: 'minutos',
  numero: 'número',
  numeros: 'números',
  area: 'área',
  areas: 'áreas',
  linea: 'línea',
  lineas: 'líneas',
  pelota: 'pelota',
  habria: 'habría',
  habian: 'habían',
  habia: 'había',
  seria: 'sería',
  estaria: 'estaría',
  podria: 'podría',
  deberia: 'debería',
  tendria: 'tendría',
  haria: 'haría',
  iria: 'iría',
  informacion: 'información',
  atencion: 'atención',
  intencion: 'intención',
  direccion: 'dirección',
  relacion: 'relación',
  situacion: 'situación',
  comunicacion: 'comunicación',
  evaluacion: 'evaluación',
  preparacion: 'preparación',
  concentracion: 'concentración',
  coordinacion: 'coordinación',
  organizacion: 'organización',
  participacion: 'participación',
  descripcion: 'descripción',
  observacion: 'observación',
  correccion: 'corrección',
  decision: 'decisión',
  decisiones: 'decisiones',
  vision: 'visión',
  revision: 'revisión',
  precision: 'precisión',
  intensidad: 'intensidad',
  volumen: 'volumen',
  objetivo: 'objetivo',
  objetivos: 'objetivos',
  consigna: 'consigna',
  consignas: 'consignas',

  // ── Faltas típicas ────────────────────────────────────────────────────────
  ahcer: 'hacer',
  acer: 'hacer',
  haci: 'hace',
  ahi: 'ahí',
  porqe: 'porque',
  porq: 'porque',
  qeu: 'que',
  qe: 'que',
  xq: 'porque',
  tmb: 'también',
  tbn: 'también',
  dps: 'después',
  pal: 'para el',
  paq: 'para que',
  entocnes: 'entonces',
  entoces: 'entonces',
  entonce: 'entonces',
  desspues: 'después',
  despeus: 'después',
  hambiente: 'ambiente',
  habiente: 'ambiente',
  exito: 'éxito',
  exitoo: 'éxito',
  problemaa: 'problema',
  imortante: 'importante',
  imporante: 'importante',
  importnte: 'importante',
  neceista: 'necesita',
  necestia: 'necesita',
  necesaita: 'necesita',
  trbajo: 'trabajo',
  trabjo: 'trabajo',
  trabaho: 'trabajo',
  eqipo: 'equipo',
  euqipo: 'equipo',
  equpo: 'equipo',
  jugarores: 'jugadores',
  jugadors: 'jugadores',
  jugaores: 'jugadores',
  jugadore: 'jugadores',
  entrenadoor: 'entrenador',
  entrenadaor: 'entrenador',
  entenador: 'entrenador',
  entrenmaiento: 'entrenamiento',
  enternamiento: 'entrenamiento',
  entrenaminto: 'entrenamiento',
  entrenamienot: 'entrenamiento',
  entrenamieto: 'entrenamiento',
  calentamieto: 'calentamiento',
  calentamineto: 'calentamiento',
  calentameinto: 'calentamiento',
  estirameintos: 'estiramientos',
  estirameinto: 'estiramiento',

  // ── Vocabulario de fútbol ─────────────────────────────────────────────────
  sesion: 'sesión',
  sesiones: 'sesiones',
  microciclo: 'microciclo',
  microciclos: 'microciclos',
  mesociclo: 'mesociclo',
  morfociclo: 'morfociclo',
  pretemporada: 'pretemporada',
  competicion: 'competición',
  competiciones: 'competiciones',
  convocatoría: 'convocatoria',
  convocatoira: 'convocatoria',
  convocatoroa: 'convocatoria',
  posesion: 'posesión',
  posesiones: 'posesiones',
  posecion: 'posesión',
  poseción: 'posesión',
  transicion: 'transición',
  transiciones: 'transiciones',
  transisión: 'transición',
  presion: 'presión',
  presiones: 'presiones',
  pressing: 'presión',
  basculacion: 'basculación',
  basculaciones: 'basculaciones',
  amplitud: 'amplitud',
  profundidad: 'profundidad',
  progresion: 'progresión',
  progresiones: 'progresiones',
  finalizacion: 'finalización',
  finalizaciones: 'finalizaciones',
  definicion: 'definición',
  definiciones: 'definiciones',
  creacion: 'creación',
  orientacion: 'orientación',
  combinacion: 'combinación',
  combinaciones: 'combinaciones',
  conservacion: 'conservación',
  activacion: 'activación',
  recuperacion: 'recuperación',
  prevencion: 'prevención',
  rehabilitacion: 'rehabilitación',
  duracion: 'duración',
  formacion: 'formación',
  formaciones: 'formaciones',
  posicion: 'posición',
  posiciones: 'posiciones',
  porteria: 'portería',
  porterias: 'porterías',
  balon: 'balón',
  balones: 'balones',
  rondo: 'rondo',
  rondos: 'rondos',
  repliegue: 'repliegue',
  contraataque: 'contraataque',
  contraataques: 'contraataques',
  desmarque: 'desmarque',
  desmarques: 'desmarques',
  cobertura: 'cobertura',
  coberturas: 'coberturas',
  vigilancia: 'vigilancia',
  vigilancias: 'vigilancias',
  basculacionn: 'basculación',
  marcaje: 'marcaje',
  marcajes: 'marcajes',
  bloque: 'bloque',
  porteros: 'porteros',
  portero: 'portero',
  laterales: 'laterales',
  central: 'central',
  centrales: 'centrales',
  mediocentro: 'mediocentro',
  mediocentros: 'mediocentros',
  extremo: 'extremo',
  extremos: 'extremos',
  delantero: 'delantero',
  delanteros: 'delanteros',
  delanteroocentro: 'delantero centro',
  mediapunta: 'mediapunta',
  interior: 'interior',
  interiores: 'interiores',
  pivot: 'pivote',
  pivote: 'pivote',
  falso9: 'falso 9',
  abp: 'ABP',
  saque: 'saque',
  corners: 'córners',
  corner: 'córner',
  cornerss: 'córners',
  falta: 'falta',
  faltas: 'faltas',
  penal: 'penalti',
  penalti: 'penalti',
  penaltis: 'penaltis',
  fuera: 'fuera',
  offside: 'fuera de juego',
  lesionado: 'lesionado',
  lesionados: 'lesionados',
  lesion: 'lesión',
  lesiones: 'lesiones',
  edema: 'edema',
  sobrecarga: 'sobrecarga',
  isquio: 'isquiosural',
  isquios: 'isquiosurales',
  isquiotibial: 'isquiosural',
  isquiotibiales: 'isquiosurales',
  adductores: 'aductores',
  aductor: 'aductor',
  aductores: 'aductores',
  cuadeiceps: 'cuádriceps',
  cuadriceps: 'cuádriceps',
  gemelo: 'gemelo',
  gemelos: 'gemelos',
  psoas: 'psoas',
  nutricion: 'nutrición',
  hidratacion: 'hidratación',
  calorico: 'calórico',
  calorica: 'calórica',
  rival: 'rival',
  rivales: 'rivales',
  scouting: 'análisis del rival',
  informe: 'informe',
  pizarra: 'pizarra',
  grafico: 'gráfico',
  graficos: 'gráficos',
  videoanalisis: 'videoanálisis',
  videoanalsis: 'videoanálisis',
  videoanalis: 'videoanálisis',
  calentamiento: 'calentamiento',
  vuelta: 'vuelta',
  desarrollo: 'desarrollo',
  tarea: 'tarea',
  tareas: 'tareas',
  ejercicio: 'ejercicio',
  ejercicios: 'ejercicios',
  variante: 'variante',
  variantes: 'variantes',
  serie: 'serie',
  series: 'series',
  repeticion: 'repetición',
  repeticiones: 'repeticiones',
  descanso: 'descanso',
  descansos: 'descansos',
  densidad: 'densidad',
  complejidad: 'complejidad',
  oposicion: 'oposición',
  espacio: 'espacio',
  espacios: 'espacios',
  campo: 'campo',
  medio: 'medio',
  completo: 'completo',
  reducido: 'reducido',
  partido: 'partido',
  partidos: 'partidos',
  amistoso: 'amistoso',
  oficial: 'oficial',
  local: 'local',
  visitante: 'visitante',
  banquillo: 'banquillo',
  titular: 'titular',
  titulares: 'titulares',
  suplente: 'suplente',
  suplentes: 'suplentes',
  cambio: 'cambio',
  cambios: 'cambios',
  gol: 'gol',
  goles: 'goles',
  asistencia: 'asistencia',
  asistencias: 'asistencias',
  ocacion: 'ocasión',
  ocasion: 'ocasión',
  ocasiones: 'ocasiones',
  disparo: 'disparo',
  disparos: 'disparos',
  centro: 'centro',
  centros: 'centros',
  pase: 'pase',
  pases: 'pases',
  conduccion: 'conducción',
  control: 'control',
  recpcion: 'recepción',
  recepcion: 'recepción',
  regate: 'regate',
  disparoalejado: 'disparo alejado',
  unoVsuno: '1v1',
  dosv2: '2v2',
}

/** Frases gramaticales seguras (no homógrafas). */
export const PHRASE_CORRECTIONS: Array<[RegExp, string]> = [
  [/\ba el\b/g, 'al'],
  [/\bde el\b/g, 'del'],
  [/\ba los jugadores se le\b/gi, 'a los jugadores se les'],
  [/\bse le pide a los\b/gi, 'se les pide a los'],
  [/\bhaci que\b/gi, 'así que'],
  [/\ben base a\b/gi, 'con base en'],
  [/\bdeacuerdo\b/gi, 'de acuerdo'],
  [/\ba parte de\b/gi, 'aparte de'],
  [/\bsinembargo\b/gi, 'sin embargo'],
  [/\bpor lo tanto\b/g, 'por lo tanto'],
  [/\btal y como\b/g, 'tal y como'],
  [/\bfuera de juego\b/gi, 'fuera de juego'],
  [/\bbalon parado\b/gi, 'balón parado'],
  [/\bjuego de posicion\b/gi, 'juego de posición'],
  [/\bjuego de posición\b/gi, 'juego de posición'],
  [/\bataque organizado\b/gi, 'ataque organizado'],
  [/\bdefensa organizada\b/gi, 'defensa organizada'],
  [/\bpresion alta\b/gi, 'presión alta'],
  [/\bpresion media\b/gi, 'presión media'],
  [/\bpresion baja\b/gi, 'presión baja'],
  [/\bbloque bajo\b/gi, 'bloque bajo'],
  [/\bbloque medio\b/gi, 'bloque medio'],
  [/\bsalida de balon\b/gi, 'salida de balón'],
  [/\bsalida de balón\b/gi, 'salida de balón'],
  [/\bcambio de orientacion\b/gi, 'cambio de orientación'],
  [/\btercer hombre\b/gi, 'tercer hombre'],
  [/\bespacio entre lineas\b/gi, 'espacio entre líneas'],
  [/\bentre lineas\b/gi, 'entre líneas'],
  [/\bvuelta a la calma\b/gi, 'vuelta a la calma'],
  [/\bvuelta calma\b/gi, 'vuelta a la calma'],
]

export const SHORT_TYPOS: Record<string, string> = {
  qe: 'que',
  qeu: 'que',
  xq: 'porque',
  tmb: 'también',
  tbn: 'también',
  dps: 'después',
  ahi: 'ahí',
}
