import { describe, it } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const src = join(here, '..')

describe('partidos workspace and dossier export', () => {
  it('lets the match list collapse to free the board', () => {
    const page = readFileSync(join(src, 'app/(dashboard)/partidos/page.tsx'), 'utf8')
    assert.match(page, /usePartidosListCollapsed/)
    assert.match(page, /PartidosCollapsedRail/)
    assert.match(page, /Ocultar lista|toggleList/)
  })

  it('offers PDF or presentation on informe rival and match plan', () => {
    const plan = readFileSync(join(src, 'components/microciclos/PlanPartido.tsx'), 'utf8')
    const scout = readFileSync(join(src, 'components/microciclos/RivalScout.tsx'), 'utf8')
    const menu = readFileSync(join(src, 'components/rivales/ExportDossierMenu.tsx'), 'utf8')
    const presenter = readFileSync(join(src, 'components/rivales/DossierPresenter.tsx'), 'utf8')
    const sala = readFileSync(join(src, 'components/revision/PresentacionSala.tsx'), 'utf8')
    const page = readFileSync(join(src, 'app/(dashboard)/revision/[code]/page.tsx'), 'utf8')
    const player = readFileSync(join(src, 'components/video-analyzer/VideoPlayer.tsx'), 'utf8')
    const library = readFileSync(join(src, 'components/revision/RevisionLibrary.tsx'), 'utf8')
    const stage = readFileSync(join(src, 'components/revision/SalaStage.tsx'), 'utf8')
    const chrome = readFileSync(join(src, 'components/revision/salaChrome.tsx'), 'utf8')
    const salaLunes = readFileSync(join(src, 'components/microciclos/SalaLunes.tsx'), 'utf8')
    const presentar = readFileSync(join(src, 'lib/dossierPresentar.ts'), 'utf8')
    assert.match(plan, /ExportDossierMenu/)
    assert.match(scout, /ExportDossierMenu/)
    assert.match(plan, /exportPresentacionDossier\('plan'/)
    assert.match(scout, /exportPresentacionDossier\('informe'/)
    assert.match(plan, /onPresentar/)
    assert.match(scout, /onPresentar/)
    assert.match(plan, /buildPlanShow/)
    assert.match(scout, /buildInformeShow/)
    assert.match(plan, /prepareDossierSala/)
    assert.match(scout, /prepareDossierSala/)
    assert.match(plan, /prepareCharlaSala/)
    assert.match(scout, /prepareCharlaSala/)
    assert.match(plan, /onPresentarTodo/)
    assert.match(scout, /onPresentarTodo/)
    assert.match(plan, /getInformeForCharla/)
    assert.match(scout, /getPlanForCharla/)
    assert.match(salaLunes, /getPlanForCharla/)
    assert.match(salaLunes, /getInformeForCharla/)
    assert.match(plan, /PresentacionSala/)
    assert.match(scout, /PresentacionSala/)
    assert.match(plan, /DossierPresenter/)
    assert.match(scout, /DossierPresenter/)
    assert.match(plan, /ambito="partido_plan"/)
    assert.match(menu, /Presentar/)
    assert.match(menu, /Presentar todo/)
    assert.match(menu, /presentar-todo/)
    assert.match(menu, /Primero el informe del rival, luego nuestro plan/)
    assert.match(presentar, /prepareCharlaSala/)
    assert.match(presentar, /concatCharlaShow/)
    assert.match(sala, /showPresenterLabel/)
    assert.match(presenter, /showPresenterLabel/)
    assert.match(menu, /Descargar PPT/)
    assert.match(menu, /PDF/)
    assert.match(presenter, /presenterEmbed/)
    assert.match(presenter, /ClubCrest/)
    const slides = readFileSync(join(src, 'components/rivales/DossierSlides.tsx'), 'utf8')
    assert.match(slides, /TacticalBoardMini/)
    assert.match(slides, /dossier-rival-crest/)
    assert.match(sala, /DrawingOverlay/)
    assert.match(sala, /SalaReviewBar/)
    assert.match(sala, /Escanea el QR con la tablet/)
    assert.match(page, /current_clip_id/)
    assert.match(page, /PresentacionSala/)
    assert.match(page, /SalaStage/)
    assert.match(library, /SalaHostDialog/)
    assert.match(player, /presenterEmbed/)
    assert.match(stage, /presenterEmbed/)
    assert.match(stage, /SalaFloatingChrome/)
    assert.match(stage, /overflow-hidden/)
    assert.match(sala, /SalaFloatingChrome/)
    assert.match(chrome, /sala-floating-chrome/)
    assert.match(chrome, /z-50/)
    assert.match(chrome, /sala-video-fullscreen/)
    assert.match(stage, /playbackMuted/)
    assert.match(sala, /playbackMuted/)
    assert.match(player, /video-mute-toggle/)
    assert.match(player, /video-fullscreen-toggle/)
    assert.equal(plan.includes('Exportar PDF'), false)
    assert.equal(scout.includes('Exportar PDF'), false)
  })

  it('opens Informe Rival as the first match tab, linked to the rival ficha', () => {
    const panel = readFileSync(join(src, 'components/partidos/MatchDetailPanel.tsx'), 'utf8')
    const page = readFileSync(join(src, 'app/(dashboard)/partidos/page.tsx'), 'utf8')
    const tab = readFileSync(join(src, 'components/partidos/PartidoPlanRivalTab.tsx'), 'utf8')
    const rivalPage = readFileSync(join(src, 'app/(dashboard)/rivales/[id]/page.tsx'), 'utf8')
    const planIdx = panel.indexOf('value="plan-partido"')
    const rivalIdx = panel.indexOf('value="informe-rival"')
    assert.ok(rivalIdx >= 0 && rivalIdx < planIdx)
    assert.match(panel, /Informe Rival/)
    assert.match(panel, /Plan de Partido/)
    assert.equal(panel.includes('Plan del rival'), false)
    assert.match(page, /rawTab === 'plan-rival'/)
    assert.match(tab, /RivalInformeTab/)
    assert.match(tab, /Informe Rival/)
    assert.match(tab, /\/rivales\/\$\{rivalId\}\?tab=informe/)
    assert.match(rivalPage, /label: 'Informe Rival'/)
    assert.match(rivalPage, /searchParams.get\('tab'\)/)
  })
})
